src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Mileage_Rate__c</fullName>
        <label>Mileage Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Professional_Rate__c</fullName>
        <label>Professional Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rush_Mileage_Rate__c</fullName>
        <label>Special Services Mileage Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rush_Professional_Rate__c</fullName>
        <label>Special Services Professional Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rush_Travel_Wait_Rate__c</fullName>
        <label>Special Services Travel/Wait Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Travel_Wait_Rate__c</fullName>
        <label>Travel/Wait Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case_Note_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Report__r.Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report__c</fullName>
        <description>Report</description>
        <inlineHelpText>Case Report that Entry is related to</inlineHelpText>
        <label>Report</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Case Note Entries</relationshipLabel>
        <relationshipName>Case_Note_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Case Note Entry</label>
    <nameField>
        <displayFormat>Bill-{00000}</displayFormat>
        <label>Case Note Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Note Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice_Item__c.object
<CustomObject>
    <description>Records for invoice items that will be synced with Quickbooks</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <length>41</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CRR_Supervisor__c</fullName>
        <label>CRR Supervisor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Report__c</fullName>
        <description>Parent Case</description>
        <label>Case Report</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Invoice Items</relationshipLabel>
        <relationshipName>Invoice_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <description>Invoice Class related to Case Report</description>
        <label>Class</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employee_Name__c</fullName>
        <label>Employee Name</label>
        <length>36</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QB_ServiceItem_check__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used in Trigger</description>
        <label>QB ServiceItem check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <description>Service Rate for Service item</description>
        <label>Rate</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rep__c</fullName>
        <description>Rep Name for Quickbooks</description>
        <label>Rep</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_Name__c</fullName>
        <description>ISYS Report Name from Case Report</description>
        <label>Report Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Date__c</fullName>
        <description>Refers &apos;Service Date Thru&apos; under Case Report</description>
        <label>Service Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_Name__c</fullName>
        <description>Name of Service: e.g. MCM-Onsite, Travel/Wait</description>
        <label>Service Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_Units__c</fullName>
        <description>Total Hours/Units per Service item from B Professional Units or B Non-Professional.</description>
        <label>Time/Units</label>
        <precision>7</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>Invoice Item</label>
    <nameField>
        <displayFormat>Invoice Line-{00000}</displayFormat>
        <label>Invoice Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>A_Note_Approval_Date_Time__c</fullName>
        <description>A Note Approval Date / Time</description>
        <label>A Note Approval Date / Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>B_Mileage_Miles_Total__c</fullName>
        <label>B Mileage Miles Total</label>
        <summarizedField>Case_Note_Entry__c.Final_Mileage__c</summarizedField>
        <summaryFilterItems>
            <field>Case_Note_Entry__c.Rush__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>Case_Note_Entry__c.Report__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>B_Non_Professional_Hours_Total__c</fullName>
        <label>B - Non Professional Units Total</label>
        <summarizedField>Case_Note_Entry__c.Adj_Travel_Wait_Hours__c</summarizedField>
        <summaryFilterItems>
            <field>Case_Note_Entry__c.Rush__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>Case_Note_Entry__c.Report__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>B_Professional_Hours_Total__c</fullName>
        <description>B Professional Hours Total</description>
        <label>B - Professional Units Total</label>
        <summarizedField>Case_Note_Entry__c.Adj_Professional_Hours__c</summarizedField>
        <summaryFilterItems>
            <field>Case_Note_Entry__c.Rush__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryForeignKey>Case_Note_Entry__c.Report__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>B_Rush_Mileage_Miles_Total__c</fullName>
        <description>B Mileage Miles Total</description>
        <label>B Rush Mileage Miles Total</label>
        <summarizedField>Case_Note_Entry__c.Adj_Mileage__c</summarizedField>
        <summaryFilterItems>
            <field>Case_Note_Entry__c.Rush__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Case_Note_Entry__c.Report__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>B_Rush_Non_Professional_Hours_Total__c</fullName>
        <description>B - Rush Non Professional Hours Total</description>
        <label>B - Rush Non Professional Units Total</label>
        <summarizedField>Case_Note_Entry__c.Adj_Travel_Wait_Hours__c</summarizedField>
        <summaryFilterItems>
            <field>Case_Note_Entry__c.Rush__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Case_Note_Entry__c.Report__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>B_Rush_Professional_Hours_Total__c</fullName>
        <description>B - Rush Professional Hours Total</description>
        <label>B - Rush Professional Units Total</label>
        <summarizedField>Case_Note_Entry__c.Adj_Professional_Hours__c</summarizedField>
        <summaryFilterItems>
            <field>Case_Note_Entry__c.Rush__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Case_Note_Entry__c.Report__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>CRR_Assigned__c</fullName>
        <description>Sales/Marketing Rep assigned to specific Case and Case Report/Opporunity</description>
        <label>CRR Assigned</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CRR_Supervisor__c</fullName>
        <label>CRR Supervisor</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lookup Employee associated to the Report</inlineHelpText>
        <label>Employee</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Case_Reports_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Jurisdiction__c</fullName>
        <formula>TEXT ( Related_Case__r.Jurisdiction__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Jurisdiction</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mileage_Rate__c</fullName>
        <label>Mileage Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Process_B__c</fullName>
        <inlineHelpText>1 - Ready to Sync 
2 - Sync Error 
3 - Synced</inlineHelpText>
        <label>Process B</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Professional_Rate__c</fullName>
        <label>Professional Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>QBJurisdiction__c</fullName>
        <description>This field is being used in code and in the QB synch.  Please do not modify and/or delete.</description>
        <label>Jurisdiction</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QBServiceItem__c</fullName>
        <label>QB Service Item</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QB_Service_Item__c</fullName>
        <formula>Text(Related_Case__r.QB_Service_Item__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>QB Service Item</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_Name__c</fullName>
        <displayFormat>Report-{0000}</displayFormat>
        <label>Report Name</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Rush_Mileage_Rate__c</fullName>
        <label>Special Services Mileage Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rush_Professional_Rate__c</fullName>
        <label>Special Services Professional Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rush_Travel_Wait_Rate__c</fullName>
        <label>Special Services Travel/Wait Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Service_Date_Thru__c</fullName>
        <description>Service Date Thru</description>
        <label>Service Date Thru</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_Tax_Total__c</fullName>
        <formula>Service_Tax_Rate__c * ( B_Professional_Billings_Total__c +  B_Rush_Professional_Hours_Total__c +  BNonProfessionalTotal_Billing__c +   B_Rush_Professional_Billings_Total__c   )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Service Tax Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Expenses__c</fullName>
        <inlineHelpText>SUM of all supporting Case Note Entry Expenses</inlineHelpText>
        <label>Total Expenses</label>
        <summarizedField>Case_Note_Entry__c.Final_Expenses__c</summarizedField>
        <summaryForeignKey>Case_Note_Entry__c.Report__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Travel_Wait_Rate__c</fullName>
        <label>Travel/Wait Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Timesheet__c.object
<CustomObject>
    <fields>
        <fullName>Approved_Units__c</fullName>
        <description>Summation of approved units.</description>
        <label>Approved Units</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <label>Employee</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nurse_Name__c</fullName>
        <description>Name of nurse that has worked in the case.</description>
        <label>Nurse Name</label>
        <length>41</length>
        <type>Text</type>
    </fields>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>Timesheet-{00000}</displayFormat>
        <label>Timesheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>QB_Initials__c</fullName>
        <description>Used for REP name in Quickbooks.</description>
        <label>QB Initials</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CG_OpportunityHandler.cls
public class CG_OpportunityHandler{

    public static void handleOpportunities(set<ID> oIDs){
        
    List<Opportunity> toProcess = new List<Opportunity>();
    List<Invoice_Item__c> newItems = new List<Invoice_Item__c>();
    List<Invoice_Item__c> updateItems = new List<Invoice_Item__c>();
    
    List<User> userList = new List<User>();
    Map<String,String> userInitialsMap = new Map<String,String>();

    //Query Opportunities
    toProcess = [Select ID, Name, QBServiceItem__c,QB_Service_Item__c, B_Mileage_Miles_Total__c, Mileage_Rate__c,CRR_Assigned__c, QBJurisdiction__c, Total_Expenses__c, Service_Tax_Total__c, B_Non_Professional_Hours_Total__c,
    Travel_Wait_Rate__c, Professional_Rate__c, B_Professional_Hours_Total__c, Rush_Mileage_Rate__c, B_Rush_Mileage_Miles_Total__c, Rush_Travel_Wait_Rate__c,
    B_Rush_Non_Professional_Hours_Total__c, Report_Name__c, Service_Date_Thru__c, Rush_Professional_Rate__c, B_Rush_Professional_Hours_Total__c , CRR_Supervisor__c, Jurisdiction__c, Employee__r.Id, Employee__r.Name, Account.Name, Account.Owner.QB_Initials__c,   
    (Select ID,Service_Name__c, Account__c, Case_Report__c, Class__c, Employee_Name__c, Rate__c, Rep__c, QB_ServiceItem_check__c, Report_Name__c, Service_Date__c, Time_Units__c, CRR_Supervisor__c from Invoice_Items__r) from Opportunity Where ID in: oIDs];
    
    //QUery all users
    userList = [Select ID, Name, QB_Initials__c from User];
    
    for(User u: userList)
        userInitialsMap.put(u.Name,u.QB_Initials__c);
    
    for(Opportunity opp:toProcess){
            String crr = userInitialsMap.get(opp.CRR_Assigned__c);
            
            list<Invoice_Item__c> items = opp.Invoice_Items__r;
            map<String, Invoice_Item__c> itemMap = new map<String,Invoice_Item__c>();
            
            
            //Search for specific line with QB_ServiceItem_check__c is true
            for(Invoice_Item__c qbi : items){
                if(qbi.QB_ServiceItem_check__c == true)
                    itemMap.put(qbi.Service_Name__c, qbi);
            }
            
            
            System.debug('-------------------' + opp.B_Rush_Professional_Hours_Total__c + '----------------------');
            System.debug(opp.QBServiceItem__c);
            
            //Handle QB Service Item
            Invoice_Item__c qbservice = buildInvItem(opp, opp.QBServiceItem__c, opp.Professional_Rate__c, opp.B_Professional_Hours_Total__c,crr);
            
            /*if(opp.B_Rush_Professional_Hours_Total__c > 0){
                qbservice.Service_Name__c = 'MCM-On Site';
            }*/
        
        	if(qbservice.Service_Name__c == 'RUSH-MCM-On Site' || qbservice.Service_Name__c.toUpperCase().startsWith('RUSH')){
                qbservice.Service_Name__c = 'MCM-On Site';
            }
            
            qbservice.QB_ServiceItem_check__c = true;
        
            if(itemMap.containsKey(opp.QBServiceItem__c)){
                //Update that specific Item
                qbservice.id = itemMap.remove(opp.QBServiceItem__c).Id;
                updateItems.add(qbservice);
            }else{
                //Create New Item
                newItems.add(qbservice);
            }
            
            
            for(Invoice_Item__c i : items){
                if(i.QB_ServiceItem_check__c == false)
                    itemMap.put(i.Service_Name__c, i);
            }
    
            //HANDLE RUSH MCM
            Invoice_Item__c rushmcm = buildInvItem(opp, 'RUSH-MCM-On Site', opp.Rush_Professional_Rate__c, opp.B_Rush_Professional_Hours_Total__c,crr);
        	rushmcm.Service_Date__c = opp.Service_Date_Thru__c;
            if(itemMap.containsKey('RUSH-MCM-On Site')){
                //Update that specific Item
                rushmcm.id = itemMap.get('RUSH-MCM-On Site').Id;
                updateItems.add(rushmcm);
            }else{
                //Create New Item
                newItems.add(rushmcm);
            }
            
            //Handle RUSH Travel
            Invoice_Item__c rushtw = buildInvItem(opp, 'RUSH-Travel/Wait', opp.Rush_Travel_Wait_Rate__c, opp.B_Rush_Non_Professional_Hours_Total__c,crr);
            if(itemMap.containsKey('RUSH-Travel/Wait')){
                //Update that specific Item
                rushtw.id = itemMap.get('RUSH-Travel/Wait').Id;
                updateItems.add(rushtw);
            }else{
                //Create New Item
                newItems.add(rushtw);
            }
            
            //Hasndle RUSH-Mileage
            Invoice_Item__c rushmi = buildInvItem(opp, 'RUSH-Mileage', opp.Rush_Mileage_Rate__c, opp.B_Rush_Mileage_Miles_Total__c,crr);
            if(itemMap.containsKey('RUSH-Mileage')){
                //Update that specific Item
                rushmi.id = itemMap.get('RUSH-Mileage').Id;
                updateItems.add(rushmi);
            }else{
                //Create New Item
                newItems.add(rushmi);
            }
            
            //Handle Travel/Wait
            Invoice_Item__c tw = buildInvItem(opp, 'Travel/Wait', opp.Travel_Wait_Rate__c, opp.B_Non_Professional_Hours_Total__c,crr);
            if(itemMap.containsKey('Travel/Wait')){
                //Update that specific Item
                tw.id = itemMap.get('Travel/Wait').Id;
                updateItems.add(tw);
            }else{
                //Create New Item
                newItems.add(tw);
            }
            
            //Handle Mileage
            Invoice_Item__c mil = buildInvItem(opp,'Mileage' , opp.Mileage_Rate__c, opp.B_Mileage_Miles_Total__c,crr);
            if(itemMap.containsKey('Mileage')){
                //Update that specific Item
                mil.id = itemMap.get('Mileage').Id;
                updateItems.add(mil);
            }else{
                //Create New Item
                newItems.add(mil);
            }
            //Handle Expenses
            Invoice_Item__c exp = buildInvItem(opp, 'Expenses', opp.Total_Expenses__c, 1,crr);
            if(itemMap.containsKey('Expenses')){
                //Update that specific Item
                exp.id = itemMap.get('Expenses').Id;
                updateItems.add(exp);
            }else{
                //Create New Item
                newItems.add(exp);
            }
            
            //Handle Service Tax
            Invoice_Item__c tax = buildInvItem(opp, 'Service Tax', opp.Service_Tax_Total__c, 1,crr);
            if(itemMap.containsKey('Service Tax')){
                //Update that specific Item
                tax.id = itemMap.get('Service Tax').Id;
                updateItems.add(tax);
            }else{
                //Create New Item
                newItems.add(tax);
            }
            
            //Set Process B flag to "1" - Ready to Sync
             opp.Process_B__c = 1;
    }

        System.debug('newItems: '+ newItems);
		System.debug('updateItems: '+ updateItems);
        
    if(newItems.size() > 0)
        insert newItems;

    if(updateItems.size() > 0)
        update updateitems;

        update toProcess;
   
    }

    public static Invoice_Item__c buildInvItem(Opportunity opp, String sName, Decimal r, Decimal t, String ini){
        Invoice_Item__c i = new Invoice_Item__c();
            i.Service_Name__c = sName;
            i.Rate__c = r;
            i.Time_Units__c = t;
            i.Account__c = opp.Account.Name;
            i.Case_Report__c= opp.id;
            i.Class__c = opp.QBJurisdiction__c;
            i.Employee_Name__c = opp.Employee__r.Name;
            i.Rep__c = ini;
            i.Report_Name__c = opp.Report_Name__c.remove('Report-');
            i.CRR_Supervisor__c = opp.CRR_Supervisor__c;
        
        return i;
        
    }
       
    public static void handleTimesheets(set<ID> tIDs){ 
    	List<Opportunity> toProcess = new List<Opportunity>();
    	List<Timesheet__c> newTime = new List<Timesheet__c>();
    	List<Timesheet__c> updateTime = new List<Timesheet__c>();
       	
        
        //Query Opportunities
        toProcess =[SELECT id, A_Note_Approval_Date_Time__c, Employee__r.Id, Employee__r.Name, (SELECT Id, Approved_Units__c, Nurse_Name__c,Case_Report_Opportunity__c, Date_Approved__c,
        Line_Type__c, QB_Error__c, QB_Id__c,QBDuration__c, User__c from Timesheets__r),(SELECT id, CreatedBy.Name, CreatedBy.QB_Username__c, CreatedById, TotalHoursA__c, 
        Report__r.id, Report__r.A_Note_Approval_Date_Time__c, Professional_Hours__c, Travel_Wait_Hours__c from Case_Note_Entries__r) FROM Opportunity WHERE ID in: tIDs];
        
        for(Opportunity opp: toProcess){
            List<Case_Note_Entry__c> entry = opp.Case_Note_Entries__r;
            List<Timesheet__c> ts = opp.Timesheets__r; 
            Set<User> eIDs = new Set<User>();
        	
            
            //Identify all different employees 
            for(Case_Note_Entry__c e: entry){
                eIDs.add(e.CreatedBy);
            }
            
            //Map of existing time sheets for Users
            map<ID,Timesheet__c> proMap = new map<ID,Timesheet__c>();
            map<ID,Timesheet__c> traMap = new map<ID,Timesheet__c>();
            for(Timesheet__c t:ts){
                if(t.Line_Type__c == 'Travel/Wait')
                    traMap.put(t.User__c, t);
                    
                if(t.Line_Type__c == 'MCM-On Site')
                    proMap.put(t.User__c, t);
            }
            
            
            
            for(User eId : eIDs){ 
                
                Decimal pHours = 0;
            	Decimal tHours = 0;
                Timesheet__c pro = new Timesheet__c();
                
                if(proMap.containsKey(eID.Id))
                    pro = proMap.get(eID.Id);
                
                Timesheet__c tra = new Timesheet__c();
                
                if(traMap.containsKey(eId.Id))
                    tra = traMap.get(eId.Id);
                
                for(Case_Note_Entry__c e2 : entry){
                   
                    if(e2.CreatedBy == eID){
                        
                        if(e2.Professional_Hours__c != null){
                            
                        	pHours += e2.Professional_Hours__c;
                            
                        }else{
                            
                            pHours = pHours;
                            
                        }
                        if(e2.Travel_Wait_Hours__c != null){
                            
                    		tHours += e2.Travel_Wait_Hours__c; 
                            
                        }else{
                            
                            tHours=tHours;
                            
                        }
                    } 
				}
                
                pro = buildTs(opp, eId, 'MCM-On Site', pHours, pro);
                tra = buildTs(opp, eId, 'Travel/Wait', tHours, tra);
                
                if(pro.Id == null){
                    newTime.add(pro);
                }else{
                    updateTime.add(pro);
                }
                
                if(tra.Id == null){
                    newTime.add(tra);
                }else{
                    updateTime.add(tra);
                }
            }
            
            //Set Process A flag to "1" - Ready to Sync
             opp.Process_A__c = 1;
        }
        
        if(newTime.size() > 0)
            insert newTime;
        
        if(updateTime.size() > 0)
            update updateTime;
            
        if(newTime.size() > 0 || updateTime.size() > 0)
            update toProcess;
        
    }
    
    public static Timesheet__c buildTs(Opportunity opp, User ce, String tName, Decimal u, Timesheet__c ts ){
        Timesheet__c t = new Timesheet__c();
        Decimal i = u*60;
            t.Approved_Units__c = u;
        	t.QBDuration__c = 'PT'+i.round()+'M';
            t.Nurse_Name__c = ce.QB_Username__c;
        	t.Line_Type__c = tName;
            t.Case_Report_Opportunity__c = opp.id;
            t.Date_Approved__c = opp.A_Note_Approval_Date_Time__c.date();
        	t.Employee__c = opp.Employee__r.Name;
        	t.User__c = ce.Id;
        	
        	if(ts.Id != null)
        	    t.Id = ts.Id;
        	
        return t;
        
    }
}