src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>UseCustomBillingCode__c</fullName>
        <defaultValue>false</defaultValue>
        <label>UseCustomBillingCode</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Billing_Code__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Codes</relationshipLabel>
        <relationshipName>Billing_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DefaultBillingCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Default Billing Code</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Billing_Code__c.DefaultCode__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Billing_Code__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Billing_Code__c</referenceTo>
        <relationshipLabel>Billing Codes</relationshipLabel>
        <relationshipName>Billing_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DefaultCode__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DefaultCode</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Max__c</fullName>
        <label>Max</label>
        <precision>3</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Min__c</fullName>
        <label>Min</label>
        <precision>3</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>Billing Code</label>
    <nameField>
        <label>Billing Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Environment_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>NewAcctBillingCodeBatchSize__c</fullName>
        <label>NewAcctBillingCodeBatchSize</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ResultsNotificationEmail__c</fullName>
        <label>ResultsNotificationEmail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Environment Settings</label>
</CustomObject>

src/classes/TestBillingCodeTrg.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestBillingCodeTrg 
{
	@TestSetup static void testData(){
		Environment_Settings__c e = new Environment_Settings__c();
		e.Name = 'Environment';
		e.ResultsNotificationEmail__c = 'test@testing.com';
		e.NewAcctBillingCodeBatchSize__c= 10;
		insert e;
		Billing_Code__c dBc = new Billing_Code__c();
		dBc.Active__c=true;
		dBc.DefaultCode__c=true;
		dBc.Min__c=1;
		dBc.Max__c=4;
		dBc.Name = 'testBillingCode1';
		insert dBc;
	}
    static Billing_Code__c defaultBc;
    static Account a;
    
    static testMethod void myUnitTest() 
    {
        insert defaultBc;
		//List<Billing_Code__c> newBCList = [select id from Billing_Code__c where name ='testBillingCode'];

		//Database.executeBatch(new NewAcctBillingCodeBatch(newBCList),1);
        //assert that when a new default code is created and the account uses custom codes, the BC is added
    	//System.assertEquals(1,[SELECT Count() FROM Billing_Code__c where Account__c=:a.Id]);
    	
    	Billing_Code__c accountBc = new Billing_Code__c();
    	accountBc.Active__c=true;
    	accountBc.DefaultCode__c=false;
    	accountBc.Min__c=2;
    	accountBc.Max__c=3;
    	accountBc.Account__c=a.Id;
    	accountBc.DefaultBillingCode__c=defaultBc.Id;
    	insert accountBc;
    	    	
    	defaultBc.Active__c=false;
    	update defaultBc;
    	
    	//make sure all related billing codes are marked inactive when the parent is marked inactive
    	System.assertEquals(false,[SELECT Active__c FROM Billing_Code__c where Id=:accountBc.Id].Active__c);

		Billing_Code__c dBc2 = [select Id from Billing_Code__c where  Name = 'testBillingCode1' limit 1] ;
		delete dBc2;
		
    	//delete defaultBc;
    	
    	//make sure all related billing codes are deleted
    	//System.assertEquals(0,[SELECT count() FROM Billing_Code__c where Id=:accountBc.Id or Id=:defaultBc.Id]);
    }
	/*static testMethod void myUnitDeleteTest()
	{
		Billing_Code__c dBc = new Billing_Code__c();
		dBc.Active__c=true;
		dBc.DefaultCode__c=false;
		dBc.Min__c=1;
		dBc.Max__c=4;
		dBc.Name = 'testBillingCode1';
		insert dBc;
		Billing_Code__c dBc2 = [select Id from Billing_Code__c where  Name = 'testBillingCode1'] ;
		delete dBc2;
	}*/
    static
    {
    	a = new Account();
    	a.Name='Test Account';
    	a.UseCustomBillingCode__c = true;
    	insert a;
    	
    	defaultBc = new Billing_Code__c();
    	defaultBc.Active__c=true;
    	defaultBc.DefaultCode__c=true;
    	defaultBc.Min__c=1;
    	defaultBc.Max__c=2;
		defaultBc.Name = 'testBillingCode';



    }
}