src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>UseCustomBillingCode__c</fullName>
        <defaultValue>false</defaultValue>
        <label>UseCustomBillingCode</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Billing_Code__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Codes</relationshipLabel>
        <relationshipName>Billing_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DefaultBillingCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Default Billing Code</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Billing_Code__c.DefaultCode__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Billing_Code__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Billing_Code__c</referenceTo>
        <relationshipLabel>Billing Codes</relationshipLabel>
        <relationshipName>Billing_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DefaultCode__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DefaultCode</label>
        <type>Checkbox</type>
    </fields>
    <label>Billing Code</label>
    <nameField>
        <label>Billing Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Environment_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>ResultsNotificationEmail__c</fullName>
        <label>ResultsNotificationEmail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Environment Settings</label>
</CustomObject>

src/classes/NewAcctBillingCodeBatch.cls
/*

Class Name    : NewAcctBillingCodeBatch
Modified by   : Levementum LLC - James Amos
Modified On   : 04-04-2017
Description   : NewAcctBillingCodeBatch - when a billing code is create - clone it and add a new to all accounts
*/

 global class NewAcctBillingCodeBatch implements  Database.Batchable<sObject>,Database.stateful{
     List<err_CNE_Log> errLogs;

     Integer updateTotalFailedCount = 0;
     Integer updateTotalSuccessCount = 0;

     List<Billing_Code__c> bcList;

     global NewAcctBillingCodeBatch(List<Billing_Code__c> newBcList){
         bcList = newBcList;
     }
     global Database.QueryLocator start(Database.BatchableContext BC) {
         System.debug('** Start **');
         errLogs = new List<err_CNE_Log>();


         String query;
         query = 'SELECT Id FROM Account where UseCustomBillingCode__c=true';

         return Database.getQueryLocator(query);
     }

     global void execute(Database.BatchableContext BC, List<Account> scope) {
         System.debug('** Execute **');


         List<Billing_Code__c> insertList = new List<Billing_Code__c>();
         Billing_Code__c clone;

         for(Billing_Code__c nbc : bcList)
         {
             for(Account a : scope)
             {
                 clone = nbc.clone(false);
                 clone.Account__c = a.Id;
                 clone.DefaultCode__c = false;
                 clone.DefaultBillingCode__c = nbc.Id;
                 insertList.add(clone);
             }
         }

         if(insertList.size()>0)
             insert insertList;

     }
     global void finish(Database.BatchableContext BC) {
         System.debug('** Finish **');
         System.debug('** updateSuccessCount **' + updateTotalSuccessCount + ' updateFailedCount' + updateTotalFailedCount);
         AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email FROM AsyncApexJob WHERE Id = :BC.getJobId()];
         if ( Test.IsRunningTest()){
             err_CNE_Log errCNE = new err_CNE_Log('test' ,'errfields', 'updateCaseEntryNotes in CustomBillingCode', null, '');
             errLogs.add(errCNE);
         }
         if (errLogs.size() > 0 || a.NumberOfErrors > 0) {
             string email_body = '';
             Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
             String[] toAddresses = Environment_Settings__c.getInstance('Environment').ResultsNotificationEmail__c.split(';');

             mail.setToAddresses(toAddresses);
             mail.setSenderDisplayName('Salesforce Support');
             mail.setSubject('Integration error on batch process');

             email_body = 'Batch ' + a.Id + ' the following number of errors ' + a.NumberOfErrors;
             for (err_CNE_Log aLog :errLogs) {
                 email_body += String.valueOf( aLog.cneId) +  ' ' + aLog.messsage +  '<br>';
                 system.debug(aLog.messsage);
             }
             mail.setHtmlBody(email_body);
             // Send the email you have created.
             Messaging.sendEmail(new Messaging.SingleEmailMessage[]{
                     mail
             });
         }
     }


     public class err_CNE_Log {
         public String messsage;
         public String flds;
         public String src;
         public Id cneId;
         public String cneName;
         public err_CNE_Log(String msg, String fldss, String srce, Id cne_Id, String cne_Name) {
             messsage = msg;
             flds = fldss;
             src = srce;
             cneId = cne_Id;
             cneName = cne_Name;
         }
     }



}