src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Mileage_Rate__c</fullName>
        <label>Mileage Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Professional_Rate__c</fullName>
        <label>Professional Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rush_Mileage_Rate__c</fullName>
        <label>Special Services Mileage Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rush_Professional_Rate__c</fullName>
        <label>Special Services Professional Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rush_Travel_Wait_Rate__c</fullName>
        <label>Special Services Travel/Wait Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Travel_Wait_Rate__c</fullName>
        <label>Travel/Wait Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Jurisdiction__c</fullName>
        <description>State where the file is being managed.</description>
        <inlineHelpText>Select the State where the File is being managed.</inlineHelpText>
        <label>Jurisdiction</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>California-WC</fullName>
                </value>
                <value>
                    <fullName>Nevada-WC</fullName>
                </value>
                <value>
                    <fullName>New Mexico-WC</fullName>
                </value>
                <value>
                    <fullName>Arizona-WC</fullName>
                </value>
                <value>
                    <fullName>Educational Services</fullName>
                </value>
                <value>
                    <fullName>Ergo. Eval.</fullName>
                </value>
                <value>
                    <fullName>LCP</fullName>
                </value>
                <value>
                    <fullName>LMS</fullName>
                </value>
                <value>
                    <fullName>EWT</fullName>
                </value>
                <value>
                    <fullName>Seminars</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Mexico</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Ergonomic Evaluation</fullName>
                </value>
                <value>
                    <fullName>Job Analysis</fullName>
                </value>
                <value>
                    <fullName>Interactive Process</fullName>
                </value>
                <value>
                    <fullName>Life Care Plan</fullName>
                </value>
                <value>
                    <fullName>Labor Market Survey</fullName>
                </value>
                <value>
                    <fullName>Educational Services</fullName>
                </value>
                <value>
                    <fullName>Seminars</fullName>
                </value>
                <value>
                    <fullName>Expert Witness Testimony</fullName>
                </value>
                <value>
                    <fullName>Telephonic</fullName>
                </value>
                <value>
                    <fullName>DO NOT USE California-WC</fullName>
                </value>
                <value>
                    <fullName>DO NOT USE Nevada-WC</fullName>
                </value>
                <value>
                    <fullName>DO NOT USE Arizona-WC</fullName>
                </value>
                <value>
                    <fullName>DO NOT USE Ergo. Eval.</fullName>
                </value>
                <value>
                    <fullName>DO NOT USE EWT</fullName>
                </value>
                <value>
                    <fullName>DO NOT USE LMS</fullName>
                </value>
                <value>
                    <fullName>DO NOT USE LCP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Rate_Card__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Rate Cards</relationshipLabel>
        <relationshipName>Rate_Cards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Mileage_Rate__c</fullName>
        <label>Mileage Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Professional_Rate__c</fullName>
        <label>Professional Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rush_Mileage_Rate__c</fullName>
        <label>Special Services Mileage Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rush_Professional_Rate__c</fullName>
        <label>Special Services Professional Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rush_Travel_Wait_Rate__c</fullName>
        <label>Special Services Travel/Wait Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Travel_Wait_Rate__c</fullName>
        <label>Travel/Wait Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Rate Card</label>
    <nameField>
        <label>Rate Card State</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/createUpdateRates.cls
//@author : CloudTrigger Inc.
//@date : 10/10/2011
//@description :	class providing ...
public with sharing class createUpdateRates
{
    final String CLASSNAME = '\n\n**** createUpdateRates.METHODNAME()';
    String strAccId;
    Account oAcc;
    public createUpdateRates(ApexPages.StandardController controller)
    {
    	String METHODNAME = CLASSNAME.replace('METHODNAME', 'createUpdateRates') + ' - constructor';
    	system.debug(LoggingLevel.INFO, METHODNAME.replace('**** ', '**** Inside ') + '\n\n');
    	
        strAccId = controller.getId();
        oAcc = [Select a.Travel_Wait_Rate__c, a.ShippingStreet, a.ShippingState, a.ShippingPostalCode, a.ShippingCountry, a.ShippingCity, 
            a.Rush_Travel_Wait_Rate__c, a.Rush_Professional_Rate__c, a.Rush_Mileage_Rate__c, a.Professional_Rate__c, a.Mileage_Rate__c From Account a
            Where a.Id = : strAccId];	
    }
    
	//@author : CloudTrigger, Inc.
	//@date : 10/10/2011
	//@description :  this method ___
	//@paramaters : NONE
	//@returns : A PageReference
    public PageReference processMe()
    {
    	String METHODNAME = CLASSNAME.replace('METHODNAME', 'processMe');
    	system.debug(LoggingLevel.INFO, METHODNAME.replace('**** ', '**** Inside ') + '\n\n');

    	ApexPages.Message msg;
    	/*
    	// get the picklist values for the Case Jurisdiction picklist
    	Set<String> lstLegalJuris = getAllLegalJurisdiction();
    	*/
    	// get the picklist values for the Case Rate__c picklist - NEW 3-10-2012
    	Set<String> lstLegalJuris = getAllValidCaseRateValues();
    	
    	map<String, Rate_Card__c> mapRateCard = new map<String, Rate_Card__c>();
    	
    	// get list of Rate Cards based on Account Id with a name that matches one of the Case Jurisdictions
    	list<Rate_Card__c> lstRC = new list<Rate_Card__c>([Select Id, Name from Rate_Card__c Where Name in :lstLegalJuris and Account__c =: strAccId]);
    	
    	for(Rate_Card__c oRC : lstRC)
    	   mapRateCard.put(oRC.Name, oRC);
    	list<Rate_Card__c> lstToInsert = new list<Rate_Card__c>();
    	for(String strLegalJuris : lstLegalJuris)
    	{
    		if(mapRateCard.get(strLegalJuris)==null)
    		{
    			Rate_Card__c objRC = new Rate_Card__c();
    			objRC.Name = strLegalJuris;
    			objRC.Account__c = strAccId;
    			if((strLegalJuris.toUpperCase()=='CALIFORNIA-WC' && (oAcc.ShippingState=='CA' || oAcc.ShippingState=='CALIFORNIA'))
    			     || (strLegalJuris.toUpperCase()=='ARIZONA-WC' && (oAcc.ShippingState=='AZ' || oAcc.ShippingState=='ARIZONA')) 
    			     || (strLegalJuris.toUpperCase()=='NEVADA-WC' && (oAcc.ShippingState=='NV' || oAcc.ShippingState=='NEVADA')))
    			{
    				objRC.Rush_Mileage_Rate__c = oAcc.Rush_Mileage_Rate__c;
    				objRC.Rush_Professional_Rate__c = oAcc.Rush_Professional_Rate__c;
    				objRC.Rush_Travel_Wait_Rate__c = oAcc.Rush_Travel_Wait_Rate__c;
    				objRC.Travel_Wait_Rate__c = oAcc.Travel_Wait_Rate__c;
    				objRC.Mileage_Rate__c = oAcc.Mileage_Rate__c;
    				objRC.Professional_Rate__c = oAcc.Professional_Rate__c;
    			}
    			lstToInsert.add(objRC);
    		}
    	}
    	PageReference p;
    	try{
    		if(lstToInsert.size()>0)
    		   insert lstToInsert;
	    	p = new PageReference('/'+strAccId);
	    	p.setRedirect(true);
	    	if(test.isRunningTest()) {
            	throw new GenericException('IO Exception');
            }
    	}catch(exception e)
    	{
    		msg = new ApexPages.Message(ApexPages.Severity.ERROR, 'Unable to Delete.'+e);
            ApexPages.addMessage(msg);
    	}
    	return p;
    }
    
	//@author : CloudTrigger, Inc.
	//@date : 3/10/2012
	//@description :  this method ___
	//@paramaters : NONE
	//@returns : A collection of Strings
    private Set<String> getAllValidCaseRateValues()
    {
    	String METHODNAME = CLASSNAME.replace('METHODNAME', 'getAllValidCaseRateValues');
    	//system.debug(LoggingLevel.INFO, METHODNAME.replace('**** ', '**** Inside ') + '\n\n');

        Set<String> CaseRates = new Set<String>();
        Schema.DescribeFieldResult fieldResult = Case.Rate__c.getDescribe();
        list<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry f : ple)
            CaseRates.add(f.getValue());
        return CaseRates;   
    }
    
	//@author : CloudTrigger, Inc.
	//@date : 10/10/2011
	//@description :  this method ___
	//@paramaters : NONE
	//@returns : A collection of Strings
    private Set<String> getAllLegalJurisdiction()
    {
    	String METHODNAME = CLASSNAME.replace('METHODNAME', 'getAllLegalJurisdiction');
    	//system.debug(LoggingLevel.INFO, METHODNAME.replace('**** ', '**** Inside ') + '\n\n');

        Set<String> lstLegal = new Set<String>();
        Schema.DescribeFieldResult fieldResult = Case.Jurisdiction__c.getDescribe();
        list<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry f : ple)
            lstLegal.add(f.getValue());
        return lstLegal;   
    }
    
    public class GenericException extends Exception {
	}
}