src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Mileage_Rate__c</fullName>
        <label>Mileage Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Professional_Rate__c</fullName>
        <label>Professional Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rush_Mileage_Rate__c</fullName>
        <label>Special Services Mileage Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rush_Professional_Rate__c</fullName>
        <label>Special Services Professional Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rush_Travel_Wait_Rate__c</fullName>
        <label>Special Services Travel/Wait Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Travel_Wait_Rate__c</fullName>
        <label>Travel/Wait Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Jurisdiction__c</fullName>
        <description>State where the file is being managed.</description>
        <inlineHelpText>Select the State where the File is being managed.</inlineHelpText>
        <label>Jurisdiction</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>California-WC</fullName>
                </value>
                <value>
                    <fullName>Nevada-WC</fullName>
                </value>
                <value>
                    <fullName>New Mexico-WC</fullName>
                </value>
                <value>
                    <fullName>Arizona-WC</fullName>
                </value>
                <value>
                    <fullName>Educational Services</fullName>
                </value>
                <value>
                    <fullName>Ergo. Eval.</fullName>
                </value>
                <value>
                    <fullName>LCP</fullName>
                </value>
                <value>
                    <fullName>LMS</fullName>
                </value>
                <value>
                    <fullName>EWT</fullName>
                </value>
                <value>
                    <fullName>Seminars</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Rate_Card__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Rate Cards</relationshipLabel>
        <relationshipName>Rate_Cards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MCM_On_Site__c</fullName>
        <label>MCM-On Site</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Mileage_Rate__c</fullName>
        <label>Mileage Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Professional_Rate__c</fullName>
        <label>Professional Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rush_Mileage_Rate__c</fullName>
        <label>Special Services Mileage Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rush_Professional_Rate__c</fullName>
        <label>Special Services Professional Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rush_Travel_Wait_Rate__c</fullName>
        <label>Special Services Travel/Wait Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Travel_Wait_Rate__c</fullName>
        <label>Travel/Wait Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Rate Card</label>
    <nameField>
        <label>Rate Card State</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Test_createUpdateRates.cls
@isTest
private class Test_createUpdateRates {

    static testMethod void myUnitTest() {
        //Account
		Account a = new Account();
		a.Name = 'ACC';
		a.Travel_Wait_Rate__c = 100;
		a.ShippingStreet = '123';
		a.Rush_Travel_Wait_Rate__c = 123;
		a.ShippingCity = 'NYC';
		a.ShippingCountry = 'USA';
		a.ShippingPostalCode = '23233';
		a.ShippingState = 'CA';
		a.ShippingStreet = 'Street';
		a.Rush_Mileage_Rate__c = 3450;
		a.Professional_Rate__c = 230;
		a.Mileage_Rate__c = 100;
		insert a;
		
		ApexPages.StandardController sc = new ApexPages.StandardController(a);
		createUpdateRates ctl = new createUpdateRates(sc);
		
		
		Set<String> lstLegal = new Set<String>();
        Schema.DescribeFieldResult fieldResult = Case.Jurisdiction__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry f : ple) {
            lstLegal.add(f.getValue());
        }
        system.debug('---------lstLegal-----------' + lstLegal);
		
		ctl.processMe();
		
		Rate_Card__c rc = new Rate_Card__c();
		rc.Account__c = a.Id;
		rc.Name = 'CALIFORNIA-WC';
		insert rc;
		
		ctl.processMe();
		
		//Select r.Travel_Wait_Rate__c, r.Rush_Travel_Wait_Rate__c, r.Rush_Professional_Rate__c, r.Rush_Mileage_Rate__c, 
		//r.Professional_Rate__c, r.Mileage_Rate__c, r.MCM_On_Site__c, r.Account__c From Rate_Card__c r
		
    }
}