src/objects/Appointment_Visit__c.object
<CustomObject>
    <description>Appointment /  Visit</description>
    <fields>
        <fullName>Authorization_for_Telephonic_Follow_up__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This box must be completed by SDL or Supervisor authorizing telephonic follow-up for an appointment</inlineHelpText>
        <label>Authorization for Telephonic Follow-up</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Case_Manager_Attended__c</fullName>
        <description>Case Manager Attended?</description>
        <label>Case Manager Attended?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No, Telephonic Follow Up</fullName>
                </value>
                <value>
                    <fullName>Yes, case manager met with the physician separately.</fullName>
                </value>
                <value>
                    <fullName>No, case manager met with the physician separately.</fullName>
                </value>
                <value>
                    <fullName>No, CM followed up in person at a later date</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Report_Opportunity__c</fullName>
        <label>Case Report / Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Appointments / Visits</relationshipLabel>
        <relationshipName>Doctor_Visits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Appointment / Visit</label>
    <nameField>
        <displayFormat>AV-{000000}</displayFormat>
        <label>Appointment / Visit #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments / Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Billing_Code__c.object
<CustomObject>
    <fields>
        <fullName>DefaultBillingCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Default Billing Code</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Billing_Code__c.DefaultCode__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Billing_Code__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Billing_Code__c</referenceTo>
        <relationshipLabel>Billing Codes</relationshipLabel>
        <relationshipName>Billing_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LinkCommunication__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used in Case Note Entry Visualforce pages. When this option is selected, the user will see the Relate Communication History functionality on the edit and add case note entry Visualforce pages.</description>
        <inlineHelpText>If specified, when editing a Case Note Entry with this billing code, the user will have the option of relating an Open Activity and Attachment.</inlineHelpText>
        <label>Link Communication</label>
        <type>Checkbox</type>
    </fields>
    <label>Billing Code</label>
    <nameField>
        <label>Billing Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case_Note_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Billing Code</description>
        <label>Billing Code</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>INACTIVE AS OF STAFF MEETING (8/6/11)</errorMessage>
            <filterItems>
                <field>Billing_Code__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Billing_Code__c</referenceTo>
        <relationshipLabel>Case Note Entries</relationshipLabel>
        <relationshipName>Case_Note_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RelatedAttachments__c</fullName>
        <label>Related Attachments</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RelatedCommunicationHistories__c</fullName>
        <label>Related Communication Histories</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Report__c</fullName>
        <description>Report</description>
        <inlineHelpText>Case Report that Entry is related to</inlineHelpText>
        <label>Report</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Case Note Entries</relationshipLabel>
        <relationshipName>Case_Note_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Case Note Entry</label>
    <nameField>
        <displayFormat>Bill-{00000}</displayFormat>
        <label>Case Note Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Note Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CaseNoteEntryAutomation__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Billing_Code_ID__c</fullName>
        <inlineHelpText>Default Billing Code for Case Note Entry creation. MUST BE 18 Char ID</inlineHelpText>
        <label>Billing Code ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CaseNoteEntryAutomation</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Case_Manager_Attended__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Case Manager Attended</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>QBServiceItem__c</fullName>
        <label>QB Service Item</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SubmitForApprovalOpp.cls
public with sharing class SubmitForApprovalOpp {
    
    private Opportunity opp {get;set;}
    private List<Case_Note_Entry__c> caseNoteEntries {get;set;}
    
    private List<Appointment_Visit__c> appointmentVisits {get;set;}
    public Boolean appointmentError {get;set;}
    
    public Boolean hasErrors {get;set;}
    private ID pendingInfoBillingCodeID{get;set;}
    
    public SubmitForApprovalOpp(ApexPages.StandardController std){
        opp = (Opportunity)std.getRecord();
        hasErrors = false;
        appointmentError = false;
        
        //validateAppointments();
        

        //Get the Case Note Auto Creation Billing Code
        //This Billing code represents the Pending info from Nurse and Cannot be submitted until filled out
        CaseNoteEntryAutomation__c csCNE = CaseNoteEntryAutomation__c.getOrgDefaults();
        pendingInfoBillingCodeID = csCNE.Billing_Code_ID__c;

        checkForErrors();
    }
    
    private void checkForErrors(){

        queryCaseNoteEntries();
        Map<String,String> codeSet = getUniqueBillingCodes();
        Set<Id> needsEntries = new Set<Id>();
        for(Case_Note_Entry__c cne : caseNoteEntries){

            if(codeSet.keySet().contains(CNE.Billing_Code__c) 
                && ((CNE.RelatedCommunicationHistories__c == null || CNE.RelatedCommunicationHistories__c.trim() == '') 
                    && (CNE.RelatedAttachments__c == null || CNE.RelatedAttachments__c.trim() == ''))){
                needsEntries.add(cne.Id);
            }
            if(cne.Billing_Code__c == pendingInfoBillingCodeID || (cne.Billing_Code__r.DefaultBillingCode__c != NULL && cne.Billing_Code__r.DefaultBillingCode__c == pendingInfoBillingCodeID)){
                needsEntries.add(cne.Id);
                
            }
        }
        
        if(needsEntries.size() > 0){
            hasErrors = true;
        }
    }
    
    
    
    private void submitForApproval(){
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval.');
        req1.setObjectId(opp.id);
        
        req1.setSubmitterId(UserInfo.getUserId()); 
        Approval.ProcessResult result = Approval.process(req1);
        System.debug('Submitted for Appproval');
    }
    
    
    private void queryCaseNoteEntries(){
        caseNoteEntries = [SELECT Id, Billing_Code__c,Billing_Code__r.DefaultBillingCode__c,RelatedCommunicationHistories__c, RelatedAttachments__c FROM Case_Note_Entry__c WHERE Report__c = :opp.Id];
    }


    public PageReference validateCNE(){
        System.debug('validateCNE');
        queryCaseNoteEntries();
        Map<String,String> codeSet = getUniqueBillingCodes();
        Set<Id> needsEntries = new Set<Id>();
        for(Case_Note_Entry__c cne : caseNoteEntries){
            if(codeSet.keySet().contains(CNE.Billing_Code__c) && ((CNE.RelatedCommunicationHistories__c == null || CNE.RelatedCommunicationHistories__c.trim() == '') && (CNE.RelatedAttachments__c == null || CNE.RelatedAttachments__c.trim() == ''))){
                needsEntries.add(cne.Id);
                System.debug('Added to entries');
            }
            if(cne.Billing_Code__c == pendingInfoBillingCodeID || (cne.Billing_Code__r.DefaultBillingCode__c != NULL && cne.Billing_Code__r.DefaultBillingCode__c == pendingInfoBillingCodeID)){needsEntries.add(cne.Id);}
        }
        
        if(needsEntries.size() > 0){
            hasErrors = true;
            System.debug('Hasd Errors');
            PageReference editPageRef = Page.editCaseNoteEntries;
            
            editPageRef.getParameters().put('strOppId',opp.Id);
            
            String allIds = '';
            
            for(Id i : needsEntries){
                allIds += i + ',';
            }
            
            allIds = allIds.subString(0,allIds.length() -1);
            
            editPageRef.getParameters().put('SelIds',allIds);
            editPageRef.getParameters().put('doValidation','true');
            return editPageRef;
        }
        
        else{
            try{
            submitForApproval();
            }
            catch(Exception e){
                
            }
            return new PageReference('/' + opp.Id);
        }
    }
    
    private Map<String,String> getUniqueBillingCodes(){
        Map<String,String> uniqueCodes = new Map<String,String>();
        for(Billing_Code__c bc : [SELECT Id,Name FROM BIlling_Code__c WHERE LinkCommunication__c = true])
            uniqueCodes.put(bc.Id,bc.Name);
        
        return uniqueCodes;
        
    }
    
    private list<Appointment_Visit__c> queryAppointmentVisits(){
        return [SELECT id, Case_Report_Opportunity__c, Case_Manager_Attended__c, Authorization_for_Telephonic_Follow_up__c, Case_Report_Opportunity__r.QBServiceItem__c FROM Appointment_Visit__c WHERE Case_Report_Opportunity__c = :opp.Id];
    }
    
    //Added 1/15/19 by Corrao Group
    //Prevents Case Submission of an Appointment with Case Manager Attended set to "No, Telephonic Follow Up"
    //and Authorization for Telephonic Follow Up is unchecked. 
    public void validateAppointments(){
          list<Appointment_Visit__c> appList = queryAppointmentVisits();
          updateApps(appList);
          //appList = queryAppointmentVisits();
        
            for(Appointment_Visit__c av: appList){
                if(av.Case_Manager_Attended__c == 'No, Telephonic Follow Up' && !av.Authorization_for_Telephonic_Follow_up__c){
                    //System.debug('ERROR FOUND');
                    appointmentError = true;
                }
            }
    }
    
    public PageReference updateApps(list<Appointment_Visit__c> appList){
        list<Appointment_Visit__c> updateList = new list<Appointment_Visit__c>();
        
        if(opp.QBServiceItem__c == 'MCM-Tele'){
            
            for(Appointment_Visit__c av: appList){
                    if(!av.Authorization_for_Telephonic_Follow_up__c){
                        av.Authorization_for_Telephonic_Follow_up__c = true;
                        updateList.add(av);
                    }
            }
            if(updateList.size()>0)
                update updateList;
        }
       
    return null;
    }
}