src/objects/Appointment_Visit__c.object
<CustomObject>
    <description>Appointment /  Visit</description>
    <fields>
        <fullName>Case_Manager_Attended__c</fullName>
        <description>Case Manager Attended?</description>
        <label>Case Manager Attended?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No, Telephonic Follow Up</fullName>
                </value>
                <value>
                    <fullName>Yes, case manager met with the physician separately.</fullName>
                </value>
                <value>
                    <fullName>No, case manager met with the physician separately.</fullName>
                </value>
                <value>
                    <fullName>No, CM followed up in person at a later date</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Report_Opportunity__c</fullName>
        <label>Case Report / Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Appointments / Visits</relationshipLabel>
        <relationshipName>Doctor_Visits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Appointment / Visit</label>
    <nameField>
        <displayFormat>AV-{000000}</displayFormat>
        <label>Appointment / Visit #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments / Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Billing_Code__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DefaultCode__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DefaultCode</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LinkCommunication__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used in Case Note Entry Visualforce pages. When this option is selected, the user will see the Relate Communication History functionality on the edit and add case note entry Visualforce pages.</description>
        <inlineHelpText>If specified, when editing a Case Note Entry with this billing code, the user will have the option of relating an Open Activity and Attachment.</inlineHelpText>
        <label>Link Communication</label>
        <type>Checkbox</type>
    </fields>
    <label>Billing Code</label>
    <nameField>
        <label>Billing Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case_Note_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Billing Code</description>
        <label>Billing Code</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>INACTIVE AS OF STAFF MEETING (8/6/11)</errorMessage>
            <filterItems>
                <field>Billing_Code__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Billing_Code__c</referenceTo>
        <relationshipLabel>Case Note Entries</relationshipLabel>
        <relationshipName>Case_Note_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Professional_Hours_Nurse__c</fullName>
        <label>Professional Hours (Nurse)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Report__c</fullName>
        <description>Report</description>
        <inlineHelpText>Case Report that Entry is related to</inlineHelpText>
        <label>Report</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Case Note Entries</relationshipLabel>
        <relationshipName>Case_Note_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Case Note Entry</label>
    <nameField>
        <displayFormat>Bill-{00000}</displayFormat>
        <label>Case Note Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Note Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>IsContactActivewiththisAccount__c</fullName>
        <inlineHelpText>Select the status of the Contactl with this Account.</inlineHelpText>
        <label>Is Contact Active with this Account?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Temporary</fullName>
                </value>
                <value>
                    <fullName>On leave</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Other_Role__c</fullName>
        <label>&quot;Other&quot; Role</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accupuncturist</fullName>
                </value>
                <value>
                    <fullName>Cardiologist</fullName>
                </value>
                <value>
                    <fullName>Chiropractor</fullName>
                </value>
                <value>
                    <fullName>Claims Professional</fullName>
                </value>
                <value>
                    <fullName>Dermatologist</fullName>
                </value>
                <value>
                    <fullName>DME Provider</fullName>
                </value>
                <value>
                    <fullName>Doctor of Osteopathy (D.O.)</fullName>
                </value>
                <value>
                    <fullName>Employee Attorney</fullName>
                </value>
                <value>
                    <fullName>Employer</fullName>
                </value>
                <value>
                    <fullName>Employer Attorney</fullName>
                </value>
                <value>
                    <fullName>General Surgeon</fullName>
                </value>
                <value>
                    <fullName>Hand Specialist</fullName>
                </value>
                <value>
                    <fullName>Interpreter Service</fullName>
                </value>
                <value>
                    <fullName>Insurance Broker</fullName>
                </value>
                <value>
                    <fullName>Neuro-Surgeon</fullName>
                </value>
                <value>
                    <fullName>Ortho-Surgeon</fullName>
                </value>
                <value>
                    <fullName>Pain Management Specialist</fullName>
                </value>
                <value>
                    <fullName>Physiatrist</fullName>
                </value>
                <value>
                    <fullName>Physical Therapist</fullName>
                </value>
                <value>
                    <fullName>Podiatrist</fullName>
                </value>
                <value>
                    <fullName>Primary Treating Physician</fullName>
                </value>
                <value>
                    <fullName>Psychologist / Psychiatrist</fullName>
                </value>
                <value>
                    <fullName>RTW Specialist / Coordinator</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Decision Maker</fullName>
                </value>
                <value>
                    <fullName>Economic Buyer</fullName>
                </value>
                <value>
                    <fullName>Economic Decision Maker</fullName>
                </value>
                <value>
                    <fullName>Evaluator</fullName>
                </value>
                <value>
                    <fullName>Executive Sponsor</fullName>
                </value>
                <value>
                    <fullName>Influencer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Environment_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>BatchSize__c</fullName>
        <label>CustBillCodesBatchSize</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NewAcctBillingCodeBatchSize__c</fullName>
        <label>NewAcctBillingCodeBatchSize</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ResultsNotificationEmail__c</fullName>
        <label>ResultsNotificationEmail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Environment Settings</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Case_Manager_Attended__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Case Manager Attended</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>QBServiceItem__c</fullName>
        <label>QB Service Item</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Date_Thru__c</fullName>
        <description>Service Date Thru</description>
        <label>Service Date Thru</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SubmitForApprovalOpp_Test.cls
@isTest
private class SubmitForApprovalOpp_Test {
    @TestSetup static void testData() {
        Environment_Settings__c e = new Environment_Settings__c();
        e.Name = 'Environment';
        e.ResultsNotificationEmail__c = 'test@testing.com';
        e.batchSize__c = 10;
        e.NewAcctBillingCodeBatchSize__c = 10;
        insert e;
    }
    
    private static testMethod void testHasErrors(){
        
        Account a = new Account();
        
        a.Name = 'Test Account';
        
        insert a;
        
        Opportunity opp = new Opportunity(AccountId=a.Id,name='Test Opportunity 1.0', Amount=0.0, closedate=system.today(),stageName ='Submitted', Service_Date_Thru__c=system.today());
        insert opp;
        
        Billing_Code__c bill= new Billing_Code__c(name ='01 Test Report',DefaultCode__c=true,Active__c=true,LinkCommunication__c=true);
        insert bill;
        
        Case_Note_Entry__c cne = new Case_Note_Entry__c(Report__c=opp.Id, Billing_Code__c=bill.id,Professional_Hours_Nurse__c=1);
        insert cne;
        
        Test.startTest();
            ApexPages.StandardController std = new ApexPages.StandardController(opp);
            
            SubmitForApprovalOpp controller = new SubmitForApprovalOpp(std);
            System.assert(controller.hasErrors);
            
            String pageRef = controller.validateCNE().getUrl();
        Test.stopTest();
        
        
        System.assert(pageRef.containsIgnoreCase('editCaseNoteEntries'));
        
    }
    
    private static testMethod void testIsTele(){
        
        Account a = new Account();
        a.Name = 'Test Account';
        insert a;
        
        /*Contact c = new Contact();
        c.LastName = 'Test';
        c.Account = a;
        c.IsContactActivewiththisAccount__c = 'Yes';
        c.Role__c = 'Ortho-Surgeon';
        c.Other_Role__c = 'Foot Specialist';
        insert c;*/
        
        
        Opportunity opp = new Opportunity(AccountId=a.Id,name='Test Opportunity 1.0', Amount=0.0, closedate=system.today(),stageName ='Submitted', Service_Date_Thru__c=system.today(), QbServiceItem__c = 'MCM-Tele');
        insert opp;
        
        Billing_Code__c bill= new Billing_Code__c(name ='01 Test Report',DefaultCode__c=true,Active__c=true,LinkCommunication__c=true);
        insert bill;
        
        Case_Note_Entry__c cne = new Case_Note_Entry__c(Report__c=opp.Id, Billing_Code__c=bill.id,Professional_Hours_Nurse__c=1);
        insert cne;
        
        Appointment_Visit__c app = new Appointment_Visit__c(Case_Manager_Attended__c = 'Yes', Case_Report_Opportunity__c = opp.Id);
        insert app;
        
        Test.startTest();
            ApexPages.StandardController std = new ApexPages.StandardController(opp);
            
            SubmitForApprovalOpp controller = new SubmitForApprovalOpp(std);
            controller.validateAppointments();
            System.assert(controller.hasErrors);
            System.assert(!controller.appointmentError);
            
            String pageRef = controller.validateCNE().getUrl();
            
        Test.stopTest();
        
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
}