src/objects/Approval_Report__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CaseReportEmployeeName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Report / Employee Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Approval Reports</relationshipLabel>
        <relationshipName>Approval_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DateTime__c</fullName>
        <description>Date and time of the action for the given step.</description>
        <label>Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>NewActionDate__c</fullName>
        <label>New Action Date</label>
        <type>DateTime</type>
    </fields>
    <label>Approval Report</label>
    <nameField>
        <displayFormat>AH-{0000000000}</displayFormat>
        <label>Approval Report ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ApprovalReportTrgHandlerTest.cls
@isTest
private class ApprovalReportTrgHandlerTest {
	
	private static testMethod void testInsert(){
		Account acc = new Account();
		acc.Name = 'Test';
		insert acc;
		
		Opportunity opp = new Opportunity();
		opp.CloseDate = Date.TODAY();
		opp.StageName = 'New';
		opp.AccountId = acc.Id;
		opp.Name = 'Test opp';
		insert opp;
		
		Approval_Report__c ar1 = new Approval_Report__c();
		ar1.Action__c = 'Step #1: A Note Report Approval';
		ar1.CaseReportEmployeeName__c = opp.Id;
		ar1.DateTime__c = Date.TODAY().addDays(-5);
		insert ar1;
		
		Test.startTest();
		Approval_Report__c ar2 = new Approval_Report__c();
		ar2.Action__c = 'Step #2: B Note Report Approval';
		ar2.CaseReportEmployeeName__c = opp.Id;
		ar2.DateTime__c = Date.TODAY().addDays(1);
		insert ar2;
		Test.stopTest();
		
		System.assertEquals([SELECT NewActionDate__c FROM Approval_Report__c WHERE Id =: ar1.Id].NewActionDate__c,Date.TODAY().addDays(1));
	}
	
}