src/objects/Area__c.object
<CustomObject>
    <fields>
        <fullName>AssignedCaseManagers__c</fullName>
        <label>Assigned Case Manager(s)</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <defaultValue>&apos;a&apos;</defaultValue>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Area</label>
    <nameField>
        <label>Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CMAssignment__c.object
<CustomObject>
    <fields>
        <fullName>AreaCode__c</fullName>
        <formula>Area__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AreaCode</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AreaRegion__c</fullName>
        <formula>TEXT(Area__r.Region__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AreaRegion</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <referenceTo>Area__c</referenceTo>
        <relationshipLabel>CM Assignments</relationshipLabel>
        <relationshipName>CM_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CaseManagerName__c</fullName>
        <formula>CaseManager__r.FirstName +&apos; &apos;+CaseManager__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Manager Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CaseManager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CM_Assignments_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <defaultValue>&apos;A&apos;</defaultValue>
        <description>AreaId + UserId to be used to lookup the values for deletes.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>CM Assignment</label>
    <nameField>
        <displayFormat>CMA ID-{0000000000}</displayFormat>
        <label>CM Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CM Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CmAssignmentTrgHandler.cls
public with sharing class CmAssignmentTrgHandler 
{	
	public void onBeforeUpdate(CMAssignment__c[] trgNewList)
	{
		//make sure the external id changes if the case manager changes
		//this will prevent a user from changing the case manager if another record exists for that combination
		for(CMAssignment__c cma : trgNewList)
			cma.ExternalId__c = cma.AreaCode__c+':'+cma.AreaRegion__c+':'+cma.CaseManager__c;
	}
	public void onBeforeInsert(CMAssignment__c[] trgNewList)
	{
		for(CMAssignment__c cma : trgNewList)
		{
			cma.ExternalId__c = cma.AreaCode__c+':'+cma.AreaRegion__c+':'+cma.CaseManager__c;
			System.debug('CmaExternal::::'+cma.ExternalId__c);
		}
	}
	public void onAfterDelete(CMAssignment__c[] trgOldList)
	{
		Set<Id> areaIdSet = new Set<Id>();		
		for(CMAssignment__c cma : trgOldList)
		{
			areaIdSet.add(cma.Area__c);
		}
		doUpdate(areaIdSet);
	}
	public void onAfterInsert(CMAssignment__c[] trgNewList)
	{
		Set<Id> areaIdSet = new Set<Id>();
		for(CMAssignment__c cma : trgNewList)
			areaIdSet.add(cma.Area__c);
		doUpdate(areaIdSet);
	}
	public void onAfterUpdate(CMAssignment__c[] trgNewList, Map<Id,CMAssignment__c> oldMap)
	{
		Set<Id> areaIdSet = new Set<Id>();
		for(CMAssignment__c cma : trgNewList)
		{
			if(cma.CaseManager__c != oldMap.get(cma.Id).CaseManager__c)
				areaIdSet.add(cma.Area__c);
		}
		if(!areaIdSet.isEmpty())
			doUpdate(areaIdSet);
	}	
	
	private static void doUpdate(Set<Id> areaIdSet)
	{		
		List<Area__c> aList = new List<Area__c>();
		for(Area__c area : [Select a.Id, Name, (Select CaseManagerName__c From CM_Assignments__r order by CaseManagerName__c) From Area__c a where a.Id in :areaIdSet])
		{
			String names='';
			for(CMAssignment__c cma : area.CM_Assignments__r)
				names+=cma.CaseManagerName__c+';';
			area.AssignedCaseManagers__c=names;
			aList.add(area);
		}		
		if(aList.size()>0)
			update aList;						
	}
}