src/objects/Area__c.object
<CustomObject>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <defaultValue>&apos;a&apos;</defaultValue>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>Bakersfield Area</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Fresno North &amp; South</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Imperial County</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Inland Empire-Central</fullName>
                </value>
                <value>
                    <fullName>Inland Empire-North</fullName>
                </value>
                <value>
                    <fullName>Inland Empire-South</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>LA Central</fullName>
                </value>
                <value>
                    <fullName>LA Southbay</fullName>
                </value>
                <value>
                    <fullName>LA Southeast</fullName>
                </value>
                <value>
                    <fullName>LA Valley</fullName>
                </value>
                <value>
                    <fullName>Long Beach/Pasadena</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Area</label>
    <nameField>
        <label>Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <formula>TEXT(AssignmentRegion__r.Region__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CMAssignment__c.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <referenceTo>Area__c</referenceTo>
        <relationshipLabel>CM Assignments</relationshipLabel>
        <relationshipName>CM_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CaseManager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CM_Assignments_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <defaultValue>&apos;A&apos;</defaultValue>
        <description>AreaId + UserId to be used to lookup the values for deletes.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>CM Assignment</label>
    <nameField>
        <displayFormat>CMA ID-{0000000000}</displayFormat>
        <label>CM Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CM Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>AssignedArea__c</fullName>
        <label>Assigned Area</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>201</fullName>
                </value>
                <value>
                    <fullName>203</fullName>
                </value>
                <value>
                    <fullName>205</fullName>
                </value>
                <value>
                    <fullName>206</fullName>
                </value>
                <value>
                    <fullName>208</fullName>
                </value>
                <value>
                    <fullName>209</fullName>
                </value>
                <value>
                    <fullName>210</fullName>
                </value>
                <value>
                    <fullName>212</fullName>
                </value>
                <value>
                    <fullName>213</fullName>
                </value>
                <value>
                    <fullName>214</fullName>
                </value>
                <value>
                    <fullName>215</fullName>
                </value>
                <value>
                    <fullName>216</fullName>
                </value>
                <value>
                    <fullName>217</fullName>
                </value>
                <value>
                    <fullName>218</fullName>
                </value>
                <value>
                    <fullName>219</fullName>
                </value>
                <value>
                    <fullName>224</fullName>
                </value>
                <value>
                    <fullName>225</fullName>
                </value>
                <value>
                    <fullName>228</fullName>
                </value>
                <value>
                    <fullName>229</fullName>
                </value>
                <value>
                    <fullName>231</fullName>
                </value>
                <value>
                    <fullName>234</fullName>
                </value>
                <value>
                    <fullName>239</fullName>
                </value>
                <value>
                    <fullName>240</fullName>
                </value>
                <value>
                    <fullName>248</fullName>
                </value>
                <value>
                    <fullName>251</fullName>
                </value>
                <value>
                    <fullName>252</fullName>
                </value>
                <value>
                    <fullName>253</fullName>
                </value>
                <value>
                    <fullName>254</fullName>
                </value>
                <value>
                    <fullName>256</fullName>
                </value>
                <value>
                    <fullName>260</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AssignedRegion__c</fullName>
        <label>Assigned Region</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>Fresno North &amp; South</fullName>
                </value>
                <value>
                    <fullName>Ventura/Oxnard Area</fullName>
                </value>
                <value>
                    <fullName>SF South</fullName>
                </value>
                <value>
                    <fullName>SF Central &amp; North</fullName>
                </value>
                <value>
                    <fullName>SD Area South</fullName>
                </value>
                <value>
                    <fullName>SD Area North</fullName>
                </value>
                <value>
                    <fullName>Santa Barbara+North</fullName>
                </value>
                <value>
                    <fullName>San Jose &amp; South</fullName>
                </value>
                <value>
                    <fullName>SanGabriel Valley</fullName>
                </value>
                <value>
                    <fullName>Sacto Central</fullName>
                </value>
                <value>
                    <fullName>Sacto East</fullName>
                </value>
                <value>
                    <fullName>Sacto North</fullName>
                </value>
                <value>
                    <fullName>Sacto South</fullName>
                </value>
                <value>
                    <fullName>OC South</fullName>
                </value>
                <value>
                    <fullName>OC North</fullName>
                </value>
                <value>
                    <fullName>Oakland/East Bay</fullName>
                </value>
                <value>
                    <fullName>Imperial County</fullName>
                </value>
                <value>
                    <fullName>Inland Empire-South</fullName>
                </value>
                <value>
                    <fullName>Inland Empire-North</fullName>
                </value>
                <value>
                    <fullName>Inland Empire-Central</fullName>
                </value>
                <value>
                    <fullName>Long Beach/Pasadena</fullName>
                </value>
                <value>
                    <fullName>LA Valley</fullName>
                </value>
                <value>
                    <fullName>LA Southeast</fullName>
                </value>
                <value>
                    <fullName>LA Southbay</fullName>
                </value>
                <value>
                    <fullName>LA Central</fullName>
                </value>
                <value>
                    <fullName>Bakersfield Area</fullName>
                </value>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/UserTrgHandler.cls
public with sharing class UserTrgHandler 
{
	public void onAfterUpdate(User[] trgNewList, Map<Id,User> oldMap, Map<Id,User> newMap)
	{		
		Map<Id,Map<String, Set<String>>> insertDeleteByUserMap = new Map<Id,Map<String, Set<String>>>();
		Set<Id> inactiveIdSet = new Set<Id>();
		for(User u : trgNewList)
		{
			Set<String> oldAreaCode = new Set<String>();
			Set<String> newAreaCode = new Set<String>();
			Set<String> oldRegion = new Set<String>();
			Set<String> newRegion = new Set<String>();			
			User oldU = oldMap.get(u.Id);
			if(!u.IsActive && oldU.IsActive)
			{
				//just add an inactive user to the and continue - then remove all CM Assignments later
				inactiveIdSet.add(u.Id);
				continue;
			}
			//skip anything that didn't change
			if(oldU.AssignedArea__c==u.AssignedArea__c && oldU.AssignedRegion__c==u.AssignedRegion__c)
				continue;
						
			if(oldU.AssignedArea__c!=null)
			{
				for(String areaCode : oldU.AssignedArea__c.split(';'))
					oldAreaCode.add(areaCode);
			}
			if(u.AssignedArea__c!=null)
			{
				for(String areaCode : u.AssignedArea__c.split(';'))
					newAreaCode.add(areaCode);
			}
			if(oldU.AssignedRegion__c!=null)
			{
				for(String region : oldU.AssignedRegion__c.split(';'))
					oldRegion.add(region);
			}
			if(u.AssignedRegion__c!=null)
			{
				for(String region : u.AssignedRegion__c.split(';'))
					newRegion.add(region);
			}
			insertDeleteByUserMap.put(u.Id, buildKeys(u.Id, oldAreaCode,newAreaCode,oldRegion,newRegion));			
		}
		
		if(!insertDeleteByUserMap.isEmpty())
		{
			Map<String, List<Area__c>> areaByExtIdMap = new Map<String, List<Area__c>>();
			Set<String> deleteExternalIdSet = new Set<String>();
			Set<String> addExternalIdSet = new Set<String>();
			for(Map<String, Set<String>> insertDeleteMap : insertDeleteByUserMap.values())
			{
				if(insertDeleteMap.containsKey('delete'))
					deleteExternalIdSet.addAll(insertDeleteMap.get('delete'));
				if(insertDeleteMap.containsKey('insert'))
					addExternalIdSet.addAll(insertDeleteMap.get('insert'));
			}			
			for(List<CMAssignment__c> dList : [SELECT Id FROM CMAssignment__c where ExternalId__c in :deleteExternalIdSet])
				delete dList;
			
			for(Area__c area : [SELECT Id, Name, Region__c, ExternalId__c From Area__c where ExternalId__c in :addExternalIdSet])
			{
				if(!areaByExtIdMap.containsKey(area.ExternalId__c))
					areaByExtIdMap.put(area.ExternalId__c, new List<Area__c>());
				areaByExtIdMap.get(area.ExternalId__c).add(area);
			}				
							
			List<CMAssignment__c> insertList = new List<CMAssignment__c>();
			for(Id userId : insertDeleteByUserMap.keySet())
			{
				Map<String, Set<String>> insertDeleteMap = insertDeleteByUserMap.get(userId);									
				if(insertDeleteMap.containsKey('insert'))
				{
					for(String externalId : insertDeleteMap.get('insert'))
					{
						//this shouldn't happen but check in case all the areas with that number are deleted
						if(areaByExtIdMap.containsKey(externalId))
						{
							for(Area__c area : areaByExtIdMap.get(externalId))
							{
								CMAssignment__c cma = new CMAssignment__c();
								cma.Area__c = area.Id;
								cma.CaseManager__c = userId;
								cma.ExternalId__c = externalId+':'+userId;
								insertList.add(cma);
							}
						}
						//else
						//	newMap.get(userId).AssignedArea__c.addError('You attempted to add an area to this User but the area does not exist');
					}
				}				
			}
			System.debug('INSERTLIST::::'+insertList);
			if(insertList.size()>0)
				insert insertList;
		}
		if(!inactiveIdSet.isEmpty())
		{
			//for(List<CMAssignment__c> dList : [SELECT Id FROM CMAssignment__c where CaseManager__c in :inactiveIdSet])
			//	delete dList;
			EmployeeFutureClass.handleInactiveUser(inactiveIdSet);
		}
	}
	public void onAfterInsert(User[] trgNewList, Map<Id,User> newMap)
	{
		EmployeeFutureClass.handleNewUser(newMap.keySet());
	}
	private Map<String,Set<String>> buildKeys(Id userId, Set<String> oldAreaCode, Set<String> newAreaCode, Set<String> oldRegion, Set<String> newRegion)
	{
		Map<String,Set<String>> deleteInsertMap = new Map<String,Set<String>>();
		for(String areaCode : oldAreaCode)
		{
			if(!newAreaCode.contains(areaCode))
			{
				if(!deleteInsertMap.containsKey('delete'))
					deleteInsertMap.put('delete',new Set<String>());
				for(String region : newRegion)
					deleteInsertMap.get('delete').add(areaCode+':'+region+':'+userId);
			}
		}
		for(String region : oldRegion)
		{
			if(!newRegion.contains(region))
			{
				if(!deleteInsertMap.containsKey('delete'))
					deleteInsertMap.put('delete',new Set<String>());
				for(String areaCode : newAreaCode)
					deleteInsertMap.get('delete').add(areaCode+':'+region+':'+userId);
			}
		}
		for(String areaCode : newAreaCode)
		{
			if(!oldAreaCode.contains(areaCode))
			{
				if(!deleteInsertMap.containsKey('insert'))
					deleteInsertMap.put('insert',new Set<String>());
				for(String region : newRegion)
					deleteInsertMap.get('insert').add(areaCode+':'+region);
			}
		}
		for(String region : newRegion)
		{
			if(!oldRegion.contains(region))
			{
				if(!deleteInsertMap.containsKey('insert'))
					deleteInsertMap.put('insert',new Set<String>());
				for(String areaCode : newAreaCode)
					deleteInsertMap.get('insert').add(areaCode+':'+region);
			}
		}
		return deleteInsertMap;
	}
}