src/objects/Area__c.object
<CustomObject>
    <fields>
        <fullName>AreaNumber__c</fullName>
        <label>Area</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Area</label>
    <nameField>
        <label>Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Billing_Code__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DefaultCode__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DefaultCode</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Max__c</fullName>
        <label>Max</label>
        <precision>3</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Min__c</fullName>
        <label>Min</label>
        <precision>3</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>Billing Code</label>
    <nameField>
        <label>Billing Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>AreaNumber__c</fullName>
        <formula>TEXT(AssignmentRegion__r.AreaNumber__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Area</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QB_Service_Item__c</fullName>
        <description>QB Service Item</description>
        <label>QB Service Item</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ER</fullName>
                </value>
                <value>
                    <fullName>Ergo. Eval.</fullName>
                </value>
                <value>
                    <fullName>Interactive Process</fullName>
                </value>
                <value>
                    <fullName>EWT</fullName>
                </value>
                <value>
                    <fullName>Expenses</fullName>
                </value>
                <value>
                    <fullName>Job Analysis</fullName>
                </value>
                <value>
                    <fullName>LCP</fullName>
                </value>
                <value>
                    <fullName>LMS</fullName>
                </value>
                <value>
                    <fullName>Longshore-Voc</fullName>
                </value>
                <value>
                    <fullName>LTD</fullName>
                </value>
                <value>
                    <fullName>MCM-CAT</fullName>
                </value>
                <value>
                    <fullName>MCM-On Site</fullName>
                </value>
                <value>
                    <fullName>MCM-Tele</fullName>
                </value>
                <value>
                    <fullName>Mileage</fullName>
                </value>
                <value>
                    <fullName>Seminars</fullName>
                </value>
                <value>
                    <fullName>Soc. Service</fullName>
                </value>
                <value>
                    <fullName>TCM Triage</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Travel/Wait</fullName>
                </value>
                <value>
                    <fullName>VRC</fullName>
                </value>
                <value>
                    <fullName>Discount</fullName>
                </value>
                <value>
                    <fullName>RUSH-MCM-On Site</fullName>
                </value>
                <value>
                    <fullName>RUSH-Mileage</fullName>
                </value>
                <value>
                    <fullName>RUSH-Travel/Wait</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supervised_by__c</fullName>
        <description>Supervised by</description>
        <label>Supervised by</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Denise Demianeau, RN, CCM</fullName>
                </value>
                <value>
                    <fullName>Catherine Kvasnicka, RN, MSN</fullName>
                </value>
                <value>
                    <fullName>Tanya Jutting-Loumakis, MA, CCM</fullName>
                </value>
                <value>
                    <fullName>Diane Campos, General Manager</fullName>
                </value>
                <value>
                    <fullName>Alysha Calderon</fullName>
                </value>
                <value>
                    <fullName>Senior Mentor</fullName>
                </value>
                <value>
                    <fullName>Angie Jung, RN, BSN, CRRN, CCM</fullName>
                </value>
                <value>
                    <fullName>Contractor - Not Applicable</fullName>
                </value>
                <value>
                    <fullName>Whitney Boyles, RN, BSN, MS, CCM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Note_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <formula>Report__r.Related_Case__r.Assignment_Region__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Area</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Billing Code</description>
        <label>Billing Code</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>INACTIVE AS OF STAFF MEETING (8/6/11)</errorMessage>
            <filterItems>
                <field>Billing_Code__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Billing_Code__c</referenceTo>
        <relationshipLabel>Case Note Entries</relationshipLabel>
        <relationshipName>Case_Note_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Note Entry</label>
    <nameField>
        <displayFormat>Bill-{00000}</displayFormat>
        <label>Case Note Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Note Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CaseNoteEntryAutomation__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Billing_Code_ID__c</fullName>
        <inlineHelpText>Default Billing Code for Case Note Entry creation. MUST BE 18 Char ID</inlineHelpText>
        <label>Billing Code ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CaseNoteEntryAutomation</label>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Area</label>
        <referenceTo>Area__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Environment_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>BatchSize__c</fullName>
        <label>CustBillCodesBatchSize</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NewAcctBillingCodeBatchSize__c</fullName>
        <label>NewAcctBillingCodeBatchSize</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ResultsNotificationEmail__c</fullName>
        <label>ResultsNotificationEmail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Environment Settings</label>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>AssignedArea__c</fullName>
        <label>Assigned Area</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>201</fullName>
                </value>
                <value>
                    <fullName>203</fullName>
                </value>
                <value>
                    <fullName>205</fullName>
                </value>
                <value>
                    <fullName>206</fullName>
                </value>
                <value>
                    <fullName>208</fullName>
                </value>
                <value>
                    <fullName>209</fullName>
                </value>
                <value>
                    <fullName>210</fullName>
                </value>
                <value>
                    <fullName>212</fullName>
                </value>
                <value>
                    <fullName>213</fullName>
                </value>
                <value>
                    <fullName>214</fullName>
                </value>
                <value>
                    <fullName>215</fullName>
                </value>
                <value>
                    <fullName>216</fullName>
                </value>
                <value>
                    <fullName>217</fullName>
                </value>
                <value>
                    <fullName>218</fullName>
                </value>
                <value>
                    <fullName>219</fullName>
                </value>
                <value>
                    <fullName>224</fullName>
                </value>
                <value>
                    <fullName>225</fullName>
                </value>
                <value>
                    <fullName>228</fullName>
                </value>
                <value>
                    <fullName>229</fullName>
                </value>
                <value>
                    <fullName>231</fullName>
                </value>
                <value>
                    <fullName>234</fullName>
                </value>
                <value>
                    <fullName>239</fullName>
                </value>
                <value>
                    <fullName>240</fullName>
                </value>
                <value>
                    <fullName>248</fullName>
                </value>
                <value>
                    <fullName>251</fullName>
                </value>
                <value>
                    <fullName>252</fullName>
                </value>
                <value>
                    <fullName>253</fullName>
                </value>
                <value>
                    <fullName>254</fullName>
                </value>
                <value>
                    <fullName>256</fullName>
                </value>
                <value>
                    <fullName>260</fullName>
                </value>
                <value>
                    <fullName>707</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestCaseNoteEntryCreationAutomation.cls
@isTest
private class TestCaseNoteEntryCreationAutomation {
   	static List<Case_Note_Entry__c> cneList = new List<Case_Note_Entry__c>();
	static Opportunity opp;
	static testMethod void test1() 
    {
    	       
        

    	Environment_Settings__c e = new Environment_Settings__c();
		e.Name = 'Environment';
		e.ResultsNotificationEmail__c = 'test@testing.com';
		e.batchSize__c = 10;
		e.NewAcctBillingCodeBatchSize__c = 10;
		insert e;

		List<Area__c> areaList = new List<Area__c>();
    	Area__c area1 = new Area__c();    	
    	area1.Name='706';
    	area1.AreaNumber__c='1';    	
    	areaList.add(area1);
    	    	
    	Area__c area2 = new Area__c();
    	area2.Name='707';
    	area2.AreaNumber__c='2';    	
    	areaList.add(area2);
    	
    	Area__c area3 = new Area__c();
    	area3.Name='708';
    	area3.AreaNumber__c='3';    	
    	areaList.add(area3);
    	
    	Area__c area4 = new Area__c();
    	area4.Name='709';
    	area4.AreaNumber__c='4';    	
    	areaList.add(area4);
    	insert areaList;

    	//Create Primary Nurse and Covering Nurse Users

    	Profile p = [SELECT p.Name,p.Id from Profile p where p.Name='Custom - Nurse' limit 1];
    	Profile p2 = [SELECT p.Name,p.Id from Profile p where p.Name='Custom - Sr Nurse' limit 1];
    	
    	List<User> userList = new List<User>();
    	User u = new User(UserName='test@isys.com',email='test@isys.com',alias='tisys',communitynickname='tix',
		TimeZoneSidKey='America/New_York',LocaleSidKey='en_US',EmailEncodingKey='ISO-8859-1',ProfileId=p.Id,LanguageLocaleKey='en_US',
	    FirstName='Test',LastName='User',IsActive=true,AssignedArea__c='706;707;708;');
		
		User coveringNurse = new User(UserName='test2@isys.com',email='test@isys.com',alias='tisy2',communitynickname='tix2',
		TimeZoneSidKey='America/New_York',LocaleSidKey='en_US',EmailEncodingKey='ISO-8859-1',ProfileId=p2.Id,LanguageLocaleKey='en_US',
	    FirstName='Test',LastName='User',IsActive=true,AssignedArea__c='706;707;708;');
		userList.add(u);
		userList.add(coveringNurse);
		
	//	Test.startTest();
		insert userList;
		//Test.stopTest();

		List<Billing_Code__c> bcList = new List<Billing_Code__c>();

		Billing_Code__c testcode= new Billing_Code__c(name ='test',DefaultCode__c=true,Active__c=true,Min__c=0.1,Max__c=3);
        bcList.add(testcode);
        Billing_Code__c profBc= new Billing_Code__c(name ='ECT',DefaultCode__c=true,Active__c=true,Min__c=0.5,Max__c=3);
        bcList.add(profBc);
        Billing_Code__c waitBc= new Billing_Code__c(name ='T01',DefaultCode__c=true,Active__c=true,Min__c=1,Max__c=3);
        bcList.add(waitBc);        
        insert bcList;

        //Create Org Default Custom Settings
    	CaseNoteEntryAutomation__c orgDefault = CaseNoteEntryAutomation__c.getOrgDefaults();
    	orgDefault.Active__c = true;
    	orgDefault.Billing_Code_ID__c = testcode.Id;
    	upsert orgDefault;

System.runAs(u)
{
		//Create Account and Contacts
			Account a = new Account(Name='Test');
	    	insert a;
	    	Map<String, Contact> conMap = new Map<String, Contact>();
	    	Contact con = new Contact(FirstName='Test', LastName='User', AccountId = a.Id, Phone='(706)602-6963');
	    	conMap.put('706',con);
	    	Contact con2 = new Contact(FirstName='Test', LastName='User', AccountId = a.Id, Phone='(707)602-6963');
	    	conMap.put('707',con2);
	    	Contact con3 = new Contact(FirstName='Test', LastName='User', AccountId = a.Id, Phone='(708)602-6963');
	    	conMap.put('708',con3);
	    	Contact con4 = new Contact(FirstName='Test', LastName='User', AccountId = a.Id, Phone='(709)602-6963');
	    	conMap.put('709',con4);
	    	insert conMap.values();
	    	

	    	//Create Case
	    	Case c = new Case(Supervised_by__c = 'MySelf',Status = 'Open',QB_Service_Item__c = 'ER',Priority = 'High',
        					Origin = 'Web',Nature_and_History_of_Injury__c = 'Nothing',Employee_Case_Trakker__c = 'Nothing',
        					Current_Diagnosis__c = 'Fine',Jurisdiction__c = 'Jurisdiction__c OLD',
        					AssignmentRegion__c = areaList[2].Id);
	    	insert c;

	    	//Create Opp
	    	opp = new Opportunity(
	    					name='Test Opportunity 1.0',
	    					AccountId=a.Id,
	    					//Related_Case__c = c.Id,
	    					Amount=0.0,
	    					CloseDate=system.today(),
	    					stageName ='In Process',
	    					Service_Date_From__c=Date.today().addDays(-5),
	    					Service_Date_Thru__c=Date.today().addDays(-1), 
	    					Report_Submission_Date__c=system.today(),
	    					A_Note_Approval_Date_Time__c=system.today());
	        insert opp;

	        opp.Related_Case__c = c.Id;
	        update opp;

	        list<Task> tList = new list<Task>();
	        
	        for(Integer i = 0;i<500; i++){
	            Task t1 = new Task();
    	        t1.ActivityDate = System.today().addDays(-2);
    	        t1.WhatId = c.Id;
    	        t1.Subject = 'Email: Test';
    	        t1.Status = 'Completed';
	            
	            tList.add(t1);
	        }
	        
	        for(Integer i = 0;i<500; i++){
	            Task t1 = new Task();
    	        t1.ActivityDate = System.today();
    	        t1.WhatId = c.Id;
    	        t1.Subject = 'Email: Test';
    	        t1.Status = 'Completed';
	            
	            tList.add(t1);
	        }
	        
            Test.StartTest();
    	        insert tList;
    	    Test.StopTest();
            
            set<ID> tIDs = new set<ID>();
            for(Task t:tList){
                tIDs.add(t.Id);
            }
            
            tList = [Select ID, Case_Note_Entry__c,Error_Case_Note_Entry_Creation__c,ActivityDate from Task Where ID in: tIDs ];
            
            for(Task t:tList){
                if(t.ActivityDate == System.Today()){
                    System.assertEquals(true,t.Error_Case_Note_Entry_Creation__c);
                }else{
                    System.assertEquals(True, t.Case_Note_Entry__c); 
                }
                
            }
}
}
	static testMethod void test2() 
    {
    	       
        

    	Environment_Settings__c e = new Environment_Settings__c();
		e.Name = 'Environment';
		e.ResultsNotificationEmail__c = 'test@testing.com';
		e.batchSize__c = 10;
		e.NewAcctBillingCodeBatchSize__c = 10;
		insert e;

		List<Area__c> areaList = new List<Area__c>();
    	Area__c area1 = new Area__c();    	
    	area1.Name='706';
    	area1.AreaNumber__c='1';    	
    	areaList.add(area1);
    	    	
    	Area__c area2 = new Area__c();
    	area2.Name='707';
    	area2.AreaNumber__c='2';    	
    	areaList.add(area2);
    	
    	Area__c area3 = new Area__c();
    	area3.Name='708';
    	area3.AreaNumber__c='3';    	
    	areaList.add(area3);
    	
    	Area__c area4 = new Area__c();
    	area4.Name='709';
    	area4.AreaNumber__c='4';    	
    	areaList.add(area4);
    	insert areaList;

    	//Create Primary Nurse and Covering Nurse Users

    	Profile p = [SELECT p.Name,p.Id from Profile p where p.Name='Custom - Nurse' limit 1];
    	Profile p2 = [SELECT p.Name,p.Id from Profile p where p.Name='Custom - Sr Nurse' limit 1];
    	
    	List<User> userList = new List<User>();
    	User u = new User(UserName='test@isys.com',email='test@isys.com',alias='tisys',communitynickname='tix',
		TimeZoneSidKey='America/New_York',LocaleSidKey='en_US',EmailEncodingKey='ISO-8859-1',ProfileId=p.Id,LanguageLocaleKey='en_US',
	    FirstName='Test',LastName='User',IsActive=true,AssignedArea__c='706;707;708;');
		
		User coveringNurse = new User(UserName='test2@isys.com',email='test@isys.com',alias='tisy2',communitynickname='tix2',
		TimeZoneSidKey='America/New_York',LocaleSidKey='en_US',EmailEncodingKey='ISO-8859-1',ProfileId=p2.Id,LanguageLocaleKey='en_US',
	    FirstName='Test',LastName='User',IsActive=true,AssignedArea__c='706;707;708;');
		userList.add(u);
		userList.add(coveringNurse);
		
		Test.startTest();
		insert userList;
		Test.stopTest();

		List<Billing_Code__c> bcList = new List<Billing_Code__c>();

		Billing_Code__c testcode= new Billing_Code__c(name ='test',DefaultCode__c=true,Active__c=true,Min__c=0.1,Max__c=3);
        bcList.add(testcode);
        Billing_Code__c profBc= new Billing_Code__c(name ='ECT',DefaultCode__c=true,Active__c=true,Min__c=0.5,Max__c=3);
        bcList.add(profBc);
        Billing_Code__c waitBc= new Billing_Code__c(name ='T01',DefaultCode__c=true,Active__c=true,Min__c=1,Max__c=3);
        bcList.add(waitBc);        
        insert bcList;

        //Create Org Default Custom Settings
    	CaseNoteEntryAutomation__c orgDefault = CaseNoteEntryAutomation__c.getOrgDefaults();
    	orgDefault.Active__c = true;
    	orgDefault.Billing_Code_ID__c = testcode.Id;
    	upsert orgDefault;

System.runAs(u)
{
		//Create Account and Contacts
			Account a = new Account(Name='Test');
	    	insert a;
	    	Map<String, Contact> conMap = new Map<String, Contact>();
	    	Contact con = new Contact(FirstName='Test', LastName='User', AccountId = a.Id, Phone='(706)602-6963');
	    	conMap.put('706',con);
	    	Contact con2 = new Contact(FirstName='Test', LastName='User', AccountId = a.Id, Phone='(707)602-6963');
	    	conMap.put('707',con2);
	    	Contact con3 = new Contact(FirstName='Test', LastName='User', AccountId = a.Id, Phone='(708)602-6963');
	    	conMap.put('708',con3);
	    	Contact con4 = new Contact(FirstName='Test', LastName='User', AccountId = a.Id, Phone='(709)602-6963');
	    	conMap.put('709',con4);
	    	insert conMap.values();
	    	

	    	//Create Case
	    	Case c = new Case(Supervised_by__c = 'MySelf',Status = 'Open',QB_Service_Item__c = 'ER',Priority = 'High',
        					Origin = 'Web',Nature_and_History_of_Injury__c = 'Nothing',Employee_Case_Trakker__c = 'Nothing',
        					Current_Diagnosis__c = 'Fine',Jurisdiction__c = 'Jurisdiction__c OLD',
        					AssignmentRegion__c = areaList[2].Id);
	    	insert c;


	    	Task firstTask = new Task();
	    	firstTask.WhatId = c.Id;
	        firstTask.Subject = 'Email: Test';
	        firstTask.Status = 'Completed';
	        insert firstTask;


	    	//Create Opp
	    	opp = new Opportunity(
	    					name='Test Opportunity 1.0',
	    					AccountId=a.Id,
	    					//Related_Case__c = c.Id,
	    					Amount=0.0,
	    					CloseDate=system.today(),
	    					stageName ='In Process',
	    					Service_Date_From__c=Date.today(),
	    					Service_Date_Thru__c=Date.today().addDays(2), 
	    					Report_Submission_Date__c=system.today(),
	    					A_Note_Approval_Date_Time__c=system.today());
	        insert opp;


	        Opportunity opp2 = new Opportunity(
	    					name='Test Opportunity 1.0',
	    					AccountId=a.Id,
	    					//Related_Case__c = c.Id,
	    					Amount=0.0,
	    					CloseDate=system.today(),
	    					stageName ='In Process',
	    					Service_Date_From__c=Date.today(),
	    					Service_Date_Thru__c=Date.today().addDays(2), 
	    					Report_Submission_Date__c=system.today(),
	    					A_Note_Approval_Date_Time__c=system.today());
	        insert opp2;

	        opp2.Related_Case__c = c.Id;
	        update opp2;

	        opp.Related_Case__c = c.Id;
	        update opp;

	        Task t1 = new Task();
	        t1.WhatId = c.Id;
	        t1.Subject = 'Email: Test';
	        t1.Status = 'Completed';
	        insert t1;
}
    }
}