src/objects/Area__c.object
<CustomObject>
    <fields>
        <fullName>AreaNumber__c</fullName>
        <label>Area</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <defaultValue>&apos;a&apos;</defaultValue>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>Bakersfield Area</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Fresno North &amp; South</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Imperial County</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Inland Empire-Central</fullName>
                </value>
                <value>
                    <fullName>Inland Empire-North</fullName>
                </value>
                <value>
                    <fullName>Inland Empire-South</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>LA Central</fullName>
                </value>
                <value>
                    <fullName>LA Southbay</fullName>
                </value>
                <value>
                    <fullName>LA Southeast</fullName>
                </value>
                <value>
                    <fullName>LA Valley</fullName>
                </value>
                <value>
                    <fullName>Long Beach/Pasadena</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Area</label>
    <nameField>
        <label>Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CMAssignment__c.object
<CustomObject>
    <fields>
        <fullName>AreaNumber__c</fullName>
        <formula>TEXT(Area__r.AreaNumber__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AreaNumber</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <referenceTo>Area__c</referenceTo>
        <relationshipLabel>CM Assignments</relationshipLabel>
        <relationshipName>CM_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CaseManagerName__c</fullName>
        <formula>CaseManager__r.FirstName +&apos; &apos;+CaseManager__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Manager Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CaseManager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CM_Assignments_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <defaultValue>&apos;A&apos;</defaultValue>
        <description>AreaId + UserId to be used to lookup the values for deletes.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>CM Assignment</label>
    <nameField>
        <displayFormat>CMA ID-{0000000000}</displayFormat>
        <label>CM Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CM Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>AssignedArea__c</fullName>
        <label>Assigned Area</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>201</fullName>
                </value>
                <value>
                    <fullName>203</fullName>
                </value>
                <value>
                    <fullName>205</fullName>
                </value>
                <value>
                    <fullName>206</fullName>
                </value>
                <value>
                    <fullName>208</fullName>
                </value>
                <value>
                    <fullName>209</fullName>
                </value>
                <value>
                    <fullName>210</fullName>
                </value>
                <value>
                    <fullName>212</fullName>
                </value>
                <value>
                    <fullName>213</fullName>
                </value>
                <value>
                    <fullName>214</fullName>
                </value>
                <value>
                    <fullName>215</fullName>
                </value>
                <value>
                    <fullName>216</fullName>
                </value>
                <value>
                    <fullName>217</fullName>
                </value>
                <value>
                    <fullName>218</fullName>
                </value>
                <value>
                    <fullName>219</fullName>
                </value>
                <value>
                    <fullName>224</fullName>
                </value>
                <value>
                    <fullName>225</fullName>
                </value>
                <value>
                    <fullName>228</fullName>
                </value>
                <value>
                    <fullName>229</fullName>
                </value>
                <value>
                    <fullName>231</fullName>
                </value>
                <value>
                    <fullName>234</fullName>
                </value>
                <value>
                    <fullName>239</fullName>
                </value>
                <value>
                    <fullName>240</fullName>
                </value>
                <value>
                    <fullName>248</fullName>
                </value>
                <value>
                    <fullName>251</fullName>
                </value>
                <value>
                    <fullName>252</fullName>
                </value>
                <value>
                    <fullName>253</fullName>
                </value>
                <value>
                    <fullName>254</fullName>
                </value>
                <value>
                    <fullName>256</fullName>
                </value>
                <value>
                    <fullName>260</fullName>
                </value>
                <value>
                    <fullName>707</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AssignedRegion__c</fullName>
        <label>Assigned Region</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>Fresno North &amp; South</fullName>
                </value>
                <value>
                    <fullName>Ventura/Oxnard Area</fullName>
                </value>
                <value>
                    <fullName>SF South</fullName>
                </value>
                <value>
                    <fullName>SF Central &amp; North</fullName>
                </value>
                <value>
                    <fullName>SD Area South</fullName>
                </value>
                <value>
                    <fullName>SD Area North</fullName>
                </value>
                <value>
                    <fullName>Santa Barbara+North</fullName>
                </value>
                <value>
                    <fullName>San Jose &amp; South</fullName>
                </value>
                <value>
                    <fullName>SanGabriel Valley</fullName>
                </value>
                <value>
                    <fullName>Sacto Central</fullName>
                </value>
                <value>
                    <fullName>Sacto East</fullName>
                </value>
                <value>
                    <fullName>Sacto North</fullName>
                </value>
                <value>
                    <fullName>Sacto South</fullName>
                </value>
                <value>
                    <fullName>OC South</fullName>
                </value>
                <value>
                    <fullName>OC North</fullName>
                </value>
                <value>
                    <fullName>Oakland/East Bay</fullName>
                </value>
                <value>
                    <fullName>Imperial County</fullName>
                </value>
                <value>
                    <fullName>Inland Empire-South</fullName>
                </value>
                <value>
                    <fullName>Inland Empire-North</fullName>
                </value>
                <value>
                    <fullName>Inland Empire-Central</fullName>
                </value>
                <value>
                    <fullName>Long Beach/Pasadena</fullName>
                </value>
                <value>
                    <fullName>LA Valley</fullName>
                </value>
                <value>
                    <fullName>LA Southeast</fullName>
                </value>
                <value>
                    <fullName>LA Southbay</fullName>
                </value>
                <value>
                    <fullName>LA Central</fullName>
                </value>
                <value>
                    <fullName>Bakersfield Area</fullName>
                </value>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestCmAssignmentTrg.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestCmAssignmentTrg 
{
    static List<CMAssignment__c> cmaList;
    static List<User> userList = new List<User>();
    static testMethod void myUnitTest() 
    {
        /*for(CMAssignment__c cma : cmaList)
        {
        	System.debug('CaseManager:::'+cma.CaseManager__c);
        	System.debug('ExternalId:::'+cma.ExternalId__c);
        	System.debug('CaseManagerName:::'+cma.CaseManagerName__c);
        	System.debug('Area:::'+cma.Area__c);
        	System.debug('AreaNumber:::'+cma.AreaNumber__c);
        	if(cma.CaseManager__c!=userList.get(0).Id)
        		cma.CaseManager__c=userList.get(0).Id;
        }*/
        update cmaList;
        
        delete cmaList;
    }
    static
	{
		List<Area__c> areaList = new List<Area__c>();
		Profile p = [SELECT p.Name,p.Id from Profile p where p.Name='Standard User' limit 1];
    	areaList.add(new Area__c(Name='706',AreaNumber__c='1',Region__c='South'));
    	areaList.add(new Area__c(Name='707',AreaNumber__c='1',Region__c='South'));
    	areaList.add(new Area__c(Name='770',AreaNumber__c='2',Region__c='South'));
    	areaList.add(new Area__c(Name='771',AreaNumber__c='2',Region__c='South'));
    	areaList.add(new Area__c(Name='716',AreaNumber__c='3',Region__c='South'));
    	areaList.add(new Area__c(Name='717',AreaNumber__c='3',Region__c='South'));
    	areaList.add(new Area__c(Name='726',AreaNumber__c='4',Region__c='South'));
    	insert areaList;
    	
    	for(integer i=0; i<3; i++)
    	{
	    	User u = new User(UserName='test@isys.com'+i,email='test'+i+'@isys.com',alias='tisys'+i,communitynickname='tix'+i,
			TimeZoneSidKey='America/New_York',LocaleSidKey='en_US',EmailEncodingKey='ISO-8859-1',ProfileId=p.Id,LanguageLocaleKey='en_US',
	    	FirstName='Test',LastName='User',IsActive=true,AssignedArea__c='706;707;770;771;716;',AssignedRegion__c='South');
			userList.add(u);
    	}
    	Test.startTest();
    	insert userList;
		Test.stopTest();    	
    	cmaList = [Select c.Name, c.ExternalId__c, c.CaseManager__c, c.CaseManagerName__c, c.Area__c, c.AreaNumber__c From CMAssignment__c c where c.CaseManager__c in :userList];
	}
}