src/objects/Area__c.object
<CustomObject>
    <fields>
        <fullName>AreaNumber__c</fullName>
        <label>Area</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <defaultValue>&apos;a&apos;</defaultValue>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Area</label>
    <nameField>
        <label>Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>AreaNumber__c</fullName>
        <formula>TEXT(AssignmentRegion__r.AreaNumber__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Area</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AssignmentRegion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment Region</label>
        <referenceTo>Area__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Diagnosis__c</fullName>
        <description>Current Diagnosis</description>
        <inlineHelpText>If more than three diagnoses, list as 1. 2. 3. 4. etc.

For one to three diagnoses, write as narrative.</inlineHelpText>
        <label>Current Diagnosis</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Customer_Guidelines__c</fullName>
        <description>Customer Special Guidelines</description>
        <inlineHelpText>Customer Special Guidelines</inlineHelpText>
        <label>Customer Guidelines</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Employee_Case_Trakker__c</fullName>
        <label>Employee (Case Trakker)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Jurisdiction__c</fullName>
        <description>State where the file is being managed.</description>
        <inlineHelpText>Select the State where the File is being managed.</inlineHelpText>
        <label>Jurisdiction</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>California-WC</fullName>
                </value>
                <value>
                    <fullName>Nevada-WC</fullName>
                </value>
                <value>
                    <fullName>New Mexico-WC</fullName>
                </value>
                <value>
                    <fullName>Arizona-WC</fullName>
                </value>
                <value>
                    <fullName>Educational Services</fullName>
                </value>
                <value>
                    <fullName>Ergo. Eval.</fullName>
                </value>
                <value>
                    <fullName>LCP</fullName>
                </value>
                <value>
                    <fullName>LMS</fullName>
                </value>
                <value>
                    <fullName>EWT</fullName>
                </value>
                <value>
                    <fullName>Seminars</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Nature_and_History_of_Injury__c</fullName>
        <description>Nature &amp; History of Injury</description>
        <inlineHelpText>Include mechanism of Injury, date of injury, and initial symptoms.</inlineHelpText>
        <label>Nature &amp; History of Injury</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>QB_Service_Item__c</fullName>
        <description>QB Service Item</description>
        <label>QB Service Item</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ER</fullName>
                </value>
                <value>
                    <fullName>Ergo. Eval.</fullName>
                </value>
                <value>
                    <fullName>Interactive Process</fullName>
                </value>
                <value>
                    <fullName>EWT</fullName>
                </value>
                <value>
                    <fullName>Expenses</fullName>
                </value>
                <value>
                    <fullName>Job Analysis</fullName>
                </value>
                <value>
                    <fullName>LCP</fullName>
                </value>
                <value>
                    <fullName>LMS</fullName>
                </value>
                <value>
                    <fullName>Longshore-Voc</fullName>
                </value>
                <value>
                    <fullName>LTD</fullName>
                </value>
                <value>
                    <fullName>MCM-CAT</fullName>
                </value>
                <value>
                    <fullName>MCM-On Site</fullName>
                </value>
                <value>
                    <fullName>MCM-Tele</fullName>
                </value>
                <value>
                    <fullName>Mileage</fullName>
                </value>
                <value>
                    <fullName>Seminars</fullName>
                </value>
                <value>
                    <fullName>Soc. Service</fullName>
                </value>
                <value>
                    <fullName>TCM Triage</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Travel/Wait</fullName>
                </value>
                <value>
                    <fullName>VRC</fullName>
                </value>
                <value>
                    <fullName>Discount</fullName>
                </value>
                <value>
                    <fullName>RUSH-MCM-On Site</fullName>
                </value>
                <value>
                    <fullName>RUSH-Mileage</fullName>
                </value>
                <value>
                    <fullName>RUSH-Travel/Wait</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Mexico</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Ergonomic Evaluation</fullName>
                </value>
                <value>
                    <fullName>Job Analysis</fullName>
                </value>
                <value>
                    <fullName>Interactive Process</fullName>
                </value>
                <value>
                    <fullName>Life Care Plan</fullName>
                </value>
                <value>
                    <fullName>Labor Market Survey</fullName>
                </value>
                <value>
                    <fullName>Educational Services</fullName>
                </value>
                <value>
                    <fullName>Seminars</fullName>
                </value>
                <value>
                    <fullName>Expert Witness Testimony</fullName>
                </value>
                <value>
                    <fullName>Telephonic</fullName>
                </value>
                <value>
                    <fullName>DO NOT USE California-WC</fullName>
                </value>
                <value>
                    <fullName>DO NOT USE Nevada-WC</fullName>
                </value>
                <value>
                    <fullName>DO NOT USE Arizona-WC</fullName>
                </value>
                <value>
                    <fullName>DO NOT USE Ergo. Eval.</fullName>
                </value>
                <value>
                    <fullName>DO NOT USE EWT</fullName>
                </value>
                <value>
                    <fullName>DO NOT USE LMS</fullName>
                </value>
                <value>
                    <fullName>DO NOT USE LCP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supervised_by__c</fullName>
        <description>Supervised by</description>
        <label>Supervised by</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Denise Demianeau, RN, CCM</fullName>
                </value>
                <value>
                    <fullName>Catherine Kvasnicka, RN, MSN</fullName>
                </value>
                <value>
                    <fullName>Tanya Jutting-Loumakis, MA, CCM</fullName>
                </value>
                <value>
                    <fullName>Diane Campos, General Manager</fullName>
                </value>
                <value>
                    <fullName>Alysha Calderon</fullName>
                </value>
                <value>
                    <fullName>Senior Mentor</fullName>
                </value>
                <value>
                    <fullName>Angie Jung, RN, BSN, CRRN, CCM</fullName>
                </value>
                <value>
                    <fullName>Contractor - Not Applicable</fullName>
                </value>
                <value>
                    <fullName>Whitney Boyles, RN, BSN, MS, CCM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CompanyMetric__c.object
<CustomObject>
    <fields>
        <fullName>CasesClosed__c</fullName>
        <label>Cases (Closed)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CasesOpen__c</fullName>
        <label>Cases (Open)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CasesReOpened__c</fullName>
        <label>Cases (Re-Opened)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Holds month/year as the external key</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Company Metric</label>
    <nameField>
        <displayFormat>Metric-{0000000000}</displayFormat>
        <label>Company Metric Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Company Metrics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Area</label>
        <referenceTo>Area__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestBatchCompanyMetricCase.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestBatchCompanyMetricCase 
{
    static list<Case> caseList = new list<Case>();
    static testMethod void myUnitTest() 
    {
        BatchCompanyMetricCase mCase = new BatchCompanyMetricCase();
        mCase.execute(null, caseList);
        mCase.finish(null);
        CompanyMetric__c cm = [SELECT CasesOpen__c,CasesReOpened__c,CasesClosed__c FROM CompanyMetric__c WHERE ExternalId__c=:mCase.runDateMonthYear];
        System.assertEquals(2,cm.CasesOpen__c);
        System.assertEquals(1,cm.CasesReopened__c);
        System.assertEquals(1,cm.CasesClosed__c);        
    }
    static
    {    	
    	List<Area__c> areaList = new List<Area__c>();
    	Area__c area1 = new Area__c();    	
    	area1.Name='706';
    	area1.AreaNumber__c='1';    	
    	areaList.add(area1);
    	    	
    	Area__c area2 = new Area__c();
    	area2.Name='707';
    	area2.AreaNumber__c='2';    	
    	areaList.add(area2);
    	
    	Area__c area3 = new Area__c();
    	area3.Name='708';
    	area3.AreaNumber__c='3';    	
    	areaList.add(area3);
    	
    	Area__c area4 = new Area__c();
    	area4.Name='709';
    	area4.AreaNumber__c='4';    	
    	areaList.add(area4);
    	insert areaList;
    	
    	Account a = new Account(Name='Test');
    	insert a;
    	Map<String, Contact> conMap = new Map<String, Contact>();
    	Contact con = new Contact(FirstName='Test', LastName='User', AccountId = a.Id, Phone='(706)602-6963');
    	conMap.put('706',con);
    	Contact con2 = new Contact(FirstName='Test', LastName='User', AccountId = a.Id, Phone='(707)602-6963');
    	conMap.put('707',con2);
    	Contact con3 = new Contact(FirstName='Test', LastName='User', AccountId = a.Id, Phone='(708)602-6963');
    	conMap.put('708',con3);
    	Contact con4 = new Contact(FirstName='Test', LastName='User', AccountId = a.Id, Phone='(709)602-6963');
    	conMap.put('709',con4);
    	insert conMap.values();
    	
    	caseList = new List<Case>();
    	Case c;
    	for(Area__c area : areaList)
    	{
	    	c = new Case();
	    	c.ContactId = conMap.get(area.Name).Id;	    	
	        c.Supervised_by__c = 'MySelf';
	        c.Status = 'Open';
	        c.QB_Service_Item__c = 'ER';
	        c.Priority = 'High';
	        c.Origin = 'Web';
	        c.Nature_and_History_of_Injury__c = 'Nothing';
	        c.Employee_Case_Trakker__c = 'Nothing';
	        c.Current_Diagnosis__c = 'Fine';
	        c.Jurisdiction__c = 'Jurisdiction__c OLD';
	        c.QB_Service_Item__c = 'QB_Service_Item__c OLD';
	        c.AssignmentRegion__c = area.Id;        
	        caseList.add(c);
    	}
    	insert caseList;
    	
    	caseList.get(0).Status='Closed';
    	caseList.get(0).Rate__c='California';
    	caseList.get(0).Customer_Guidelines__c='my guidelines';
    	
    	caseList.get(1).Status='Re-Opened';
    	update caseList;
    	
    	caseList = [Select Id,Status,ClosedDate FROM Case WHERE Id in :caseList];
    }
}