src/objects/Area__c.object
<CustomObject>
    <fields>
        <fullName>AreaNumber__c</fullName>
        <label>Area</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <defaultValue>&apos;a&apos;</defaultValue>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Area</label>
    <nameField>
        <label>Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>AreaNumber__c</fullName>
        <formula>TEXT(AssignmentRegion__r.AreaNumber__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Area</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Employee</description>
        <label>Employee</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Open Files (Cases)</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OwnerAtCaseClose__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>store who owned the case before it was closed and transferred to a queue</description>
        <label>OwnerAtCaseClose</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CMMetric__c.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ClosedCases__c</fullName>
        <label>Closed Cases</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <label>Employee</label>
        <referenceTo>SFDC_Employee__c</referenceTo>
        <relationshipLabel>CM Metrics</relationshipLabel>
        <relationshipName>CM_Metrics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>56</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MetricDate__c</fullName>
        <label>Metric Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OpenCases__c</fullName>
        <label>Open Cases</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CM Metric</label>
    <nameField>
        <displayFormat>CMMID-{0000000000}</displayFormat>
        <label>CM Metric ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CM Metrics</pluralLabel>
    <recordTypes>
        <fullName>AreaMetric</fullName>
        <active>true</active>
        <label>Area Metric</label>
    </recordTypes>
    <recordTypes>
        <fullName>UserMetric</fullName>
        <active>true</active>
        <label>User Metric</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SFDC_Employee__c.object
<CustomObject>
    <fields>
        <fullName>SF_Username__c</fullName>
        <externalId>true</externalId>
        <label>SF Username</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchCaseMetrics.cls
global class BatchCaseMetrics implements Database.Batchable<sObject>, Database.Stateful
{
	Date runDate = Date.today();	
	integer daysInMonth = Date.daysInMonth(runDate.year(),runDate.month());	
	Date metricDate = Date.parse(String.valueOf(runDate.month())+'/'+daysInMonth+'/'+runDate.year());
	Map<String,CMMetric__c> keyMap = new Map<String, CMMetric__c>();
	String monthYear = '';
	String runDateMonthYear = String.valueOf(runDate.month()+'/'+runDate.year());
	integer currentMonth = runDate.month();
	integer currentYear = runDate.year();
	Map<String,Id> rtIdMap = new Map<String,Id>();
	global BatchCaseMetrics()
	{
		for(RecordType rt : [SELECT Id,DeveloperName FROM RecordType WHERE SobjectType='CMMetric__c'])
			rtIdMap.put(rt.DeveloperName,rt.Id);
	}
	global Database.Querylocator start(Database.Batchablecontext BC)
    {    	
    	return Database.getQueryLocator([Select Id,AreaNumber__c,OwnerId,OwnerAtCaseClose__c,Owner.Username,Owner.Type,IsClosed,ClosedDate FROM Case WHERE Status in ('Open','Re-Opened','Closed')]);
    }
    global void execute(Database.Batchablecontext BC, list<SObject> scope)
    {
    	try{
    	String areaKey;
    	String userKey;
    	Set<Id> ownerId = new Set<Id>();
    	for(Sobject so : scope)
    	{
    		Case c = (Case)so;
    		if(c.IsClosed)
    		{
    			if(c.OwnerAtCaseClose__c==null ||(c.ClosedDate.month()!=currentMonth && c.ClosedDate.year()!=currentYear))
    				continue;
    			else
    				ownerId.add(c.OwnerAtCaseClose__c);
    		}
    	}
    	Map<Id,User> userMap = new Map<Id,User>([SELECT Id,UserName FROM User WHERE Id in :ownerId]);
    	for(Sobject so : scope)
    	{
    		areaKey = null;
    		userKey = null;
    		Case c = (Case)so;    		
    		SFDC_Employee__c emp = new SFDC_Employee__c();
    		if(c.IsClosed)
    		{
    			if(c.OwnerAtCaseClose__c==null || (c.ClosedDate.month()!=currentMonth || c.ClosedDate.year()!=currentYear) || !userMap.containsKey(c.OwnerAtCaseClose__c))
    				continue;
    			monthYear = String.valueOf(c.ClosedDate.month()+'/'+c.ClosedDate.year());
    			if(c.AreaNumber__c!=null&&c.AreaNumber__c!='')
    				areaKey = c.AreaNumber__c+':'+c.OwnerAtCaseClose__c+':'+monthYear;
    			userKey = c.OwnerAtCaseClose__c+':'+monthYear;
    			    			    				
    			emp.SF_Username__c = userMap.get(c.OwnerAtCaseClose__c).UserName;
    			
    			if(areaKey!=null)
    			{
    				if(!keyMap.containsKey(areaKey))
    					keyMap.put(areaKey, new CMMetric__c(ExternalId__c=areaKey,OpenCases__c=0,ClosedCases__c=0,Employee__r=emp, Area__c=c.AreaNumber__c, MetricDate__c=metricDate,RecordTypeId=rtIdMap.get('AreaMetric')));
    				keyMap.get(areaKey).ClosedCases__c+=1;
    			}
    			if(!keyMap.containsKey(userKey))
    				keyMap.put(userKey, new CMMetric__c(ExternalId__c=userKey,OpenCases__c=0,ClosedCases__c=0,Employee__r=emp,MetricDate__c=metricDate,RecordTypeId=rtIdMap.get('UserMetric')));
    			keyMap.get(userKey).ClosedCases__c+=1;
    		}
    		else
    		{
    			if(c.Owner.Type!='User')
    				continue;
    			monthYear=runDateMonthYear;
    			if(c.AreaNumber__c!=null&&c.AreaNumber__c!='')
    				areaKey = c.AreaNumber__c+':'+c.OwnerId+':'+monthYear;
    			userKey = c.OwnerId+':'+monthYear;   			
    			emp.SF_Username__c = c.Owner.UserName;
    			
    			if(areaKey!=null)
    			{
    				if(!keyMap.containsKey(areaKey))
    					keyMap.put(areaKey, new CMMetric__c(ExternalId__c=areaKey,OpenCases__c=0,ClosedCases__c=0,Employee__r=emp, Area__c=c.AreaNumber__c, MetricDate__c=metricDate,RecordTypeId=rtIdMap.get('AreaMetric')));
    				keyMap.get(areaKey).OpenCases__c+=1;
    			}
    			if(!keyMap.containsKey(userKey))
    				keyMap.put(userKey, new CMMetric__c(ExternalId__c=userKey,OpenCases__c=0,ClosedCases__c=0,Employee__r=emp,MetricDate__c=metricDate,RecordTypeId=rtIdMap.get('UserMetric')));
    			keyMap.get(userKey).OpenCases__c+=1;
    		}
    	}
    	}
    	catch(Exception e){
			Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
			String[] toAddresses = new String[] {'Diane.Campos@isyscm.com '};
			mail.setToAddresses(toAddresses);
			mail.setSubject('Error Processing BatchCaseMetrics');
			mail.setPlainTextBody
			('The BatchCaseMetrics job failed. Some records may have been processed:' + '\n' + 'Message: ' + e.getMessage() + '\nStackTrace: ' + e.getStackTraceString() + '');
			Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
		}
    }
    global void finish (Database.Batchablecontext BC)
    {    	
    	upsert keyMap.values() ExternalId__c;
    	if(!Test.isRunningTest())
    		Database.executeBatch(new BatchCaseNoteEntryMetrics());
    }
}