src/objects/Area__c.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>Bakersfield Area</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Fresno North &amp; South</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Imperial County</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Inland Empire-Central</fullName>
                </value>
                <value>
                    <fullName>Inland Empire-North</fullName>
                </value>
                <value>
                    <fullName>Inland Empire-South</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>LA Central</fullName>
                </value>
                <value>
                    <fullName>LA Southbay</fullName>
                </value>
                <value>
                    <fullName>LA Southeast</fullName>
                </value>
                <value>
                    <fullName>LA Valley</fullName>
                </value>
                <value>
                    <fullName>Long Beach/Pasadena</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Area</label>
    <nameField>
        <label>Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>AreaCodePhone__c</fullName>
        <formula>MID(Phone,2,3)</formula>
        <label>Area Code (Phone)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Area__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Area</label>
        <referenceTo>Area__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>Bakersfield Area</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Fresno North &amp; South</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Imperial County</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Inland Empire-Central</fullName>
                </value>
                <value>
                    <fullName>Inland Empire-North</fullName>
                </value>
                <value>
                    <fullName>Inland Empire-South</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>LA Central</fullName>
                </value>
                <value>
                    <fullName>LA Southbay</fullName>
                </value>
                <value>
                    <fullName>LA Southeast</fullName>
                </value>
                <value>
                    <fullName>LA Valley</fullName>
                </value>
                <value>
                    <fullName>Long Beach/Pasadena</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Healthcare_Provider__c.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Area</label>
        <referenceTo>Area__c</referenceTo>
        <relationshipLabel>Healthcare Providers</relationshipLabel>
        <relationshipName>Healthcare_Providers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact</description>
        <inlineHelpText>Healthcare Provider</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Other_Healthcare_Providers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Previous, but inactive treaters on the case</description>
        <inlineHelpText>Designate a Healthcare Provider as inactive when the Employee is no longer treating with them</inlineHelpText>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Primary</description>
        <inlineHelpText>Only one physician can be designated as Primary Health Care Provider.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProviderStatus__c</fullName>
        <label>Provider Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Bakersfield Area</fullName>
                </value>
                <value>
                    <fullName>Fresno North &amp; South</fullName>
                </value>
                <value>
                    <fullName>Imperial County</fullName>
                </value>
                <value>
                    <fullName>Inland Empire-Central</fullName>
                </value>
                <value>
                    <fullName>Inland Empire-South</fullName>
                </value>
                <value>
                    <fullName>LA Central</fullName>
                </value>
                <value>
                    <fullName>LA Southbay</fullName>
                </value>
                <value>
                    <fullName>LA Southeast</fullName>
                </value>
                <value>
                    <fullName>LA Valley</fullName>
                </value>
                <value>
                    <fullName>Long Beach/Pasadena</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>Oakland/East Bay</fullName>
                </value>
                <value>
                    <fullName>OC North</fullName>
                </value>
                <value>
                    <fullName>OC South</fullName>
                </value>
                <value>
                    <fullName>Sacto Central</fullName>
                </value>
                <value>
                    <fullName>Sacto North</fullName>
                </value>
                <value>
                    <fullName>SanGabriel Valley</fullName>
                </value>
                <value>
                    <fullName>San Jose &amp; South</fullName>
                </value>
                <value>
                    <fullName>Santa Barbara+North</fullName>
                </value>
                <value>
                    <fullName>SD Area North</fullName>
                </value>
                <value>
                    <fullName>SD Area South</fullName>
                </value>
                <value>
                    <fullName>SF Central &amp; North</fullName>
                </value>
                <value>
                    <fullName>SF South</fullName>
                </value>
                <value>
                    <fullName>Ventura/Oxnard Area</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Healthcare Provider</label>
    <nameField>
        <displayFormat>HP-{000000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Healthcare Providers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ContactTriggerHandler.cls
public with sharing class ContactTriggerHandler
{
	List<Contact> oldRecords, newRecords;
    Map<Id,Contact> oldRecordsMap,newRecordsMap;
   
    public ContactTriggerHandler(List<Contact> newRecords, List<Contact> oldRecords, Map<Id,Contact> newRecordsMap, Map<Id,Contact> oldRecordsMap)
    {
		this.oldRecords = oldRecords;
	    this.newRecords = newRecords;
	    this.oldRecordsMap = oldRecordsMap;
	    this.newRecordsMap = newRecordsMap;
    }//end constructor
    
	public void processBeforeInsert()
	{
		List<String> areaCodes = new List<String>();
		List<String> regions = new List<String>();
		//If both the phone and the region are set, the Area on the Contact needs to be updated
		for(Contact c: newRecords)
		{
			if((c.Phone != null) && (c.Region__c!= null))
			{
				areaCodes.add(c.AreaCodePhone__c);
				regions.add(c.Region__c);
			}
		}//end for
		if(!areaCodes.isEmpty()&& !regions.isEmpty())
		{
			Map<String,Id> areaMap = getAreaMap(areaCodes, regions);
			//Now iterate all the contacts and put areas on them
			for(Contact c: newRecords)
			{
				if((c.Phone != null)&& (c.Region__c!= null))
				{
					String areaKey = c.AreaCodePhone__c + c.Region__c;
					if(areaKey!= null && areaMap.containsKey(areaKey))
					{
						c.Area__c = areaMap.get(areaKey);
					}
				}//end null check on phone and region
			}//end for			
		}//end null check on areas and regions		
    }//end processBeforeInsert()
    
    public void processAfterUpdate()
    {
    	//if the phone changes, send an update to the healthcare provider list so the trigger can make changes to area if necessary
		Set<Id> changedContactIdSet = new Set<Id>();
		for(Contact c : newRecords)
		{
			if(c.Phone != oldRecordsMap.get(c.Id).Phone)
				changedContactIdSet.add(c.Id);
		}
		if(changedContactIdSet.size()>0)
		{
			//query for any related healthcare provider that's primary and active
			//for(List<Healthcare_Provider__c> hcpList : [SELECT Id FROM Healthcare_Provider__c where Contact__c in :changedContactIdSet and InActive__c=false and Primary__c=true])
			for(List<Healthcare_Provider__c> hcpList : [SELECT Id FROM Healthcare_Provider__c where Contact__c in :changedContactIdSet and ProviderStatus__c='Active' and Primary__c=true])
				update hcpList;
		}
    }//end processAfterInsert()
   
    public void processBeforeUpdate()
    {
		List<String> areaCodes = new List<String>();
		List<String> regions = new List<String>();
		Map<Id,String> contactIdToKeyMap = new Map<Id,String>();
		
		//If either the phone or the region changes, the Area on the Contact needs to be updated
		for(Contact c: newRecords)
		{
			if((c.Phone != null && c.Phone != oldRecordsMap.get(c.Id).Phone)||(c.Region__c!= null && c.Region__c != oldRecordsMap.get(c.Id).Region__c))
			{
				areaCodes.add(c.AreaCodePhone__c);
				regions.add(c.Region__c);
				String concatenatedString = c.AreaCodePhone__c + c.Region__c;
				contactIdToKeyMap.put(c.id,concatenatedString);
			}
		}//end for
		if(!contactIdToKeyMap.isEmpty())
		{
			Map<String,Id> areaMap = getAreaMap(areaCodes, regions);	
			//Now iterate the contacts that were updated and put areas on them
			for(Id cId: contactIdToKeyMap.keySet())
			{
				String areaKey = contactIdToKeyMap.get(cId);
				if(areaKey!= null && areaMap.containsKey(areaKey))
				{
					newRecordsMap.get(cId).Area__c = areaMap.get(areaKey);
				}
			}
		}//end empty check on contactIdToKeyMap		
    }//end processBeforeUpdate()
    
    public Map<String,Id> getAreaMap(List<String>areaCodes, List<String>regions)
    {
    	Map<String,Id> areaMap = new Map<String,Id>();
		System.debug('areaCodes----'+areaCodes);
		System.debug('regions----'+regions);
    	//Query Area__c to get the matching areas
		for(Area__c area:[SELECT Id,Name,Region__c FROM Area__c where Region__c in :regions and Name in:areaCodes])
		{
			String key = area.Name + area.Region__c;
			areaMap.put(key,area.id);
		}			
		System.debug('areaMap---'+areaMap);
		return areaMap;
    }//end getAreaMap()
}