src/objects/Area__c.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>Bakersfield Area</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Fresno North &amp; South</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Imperial County</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Inland Empire-Central</fullName>
                </value>
                <value>
                    <fullName>Inland Empire-North</fullName>
                </value>
                <value>
                    <fullName>Inland Empire-South</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>LA Central</fullName>
                </value>
                <value>
                    <fullName>LA Southbay</fullName>
                </value>
                <value>
                    <fullName>LA Southeast</fullName>
                </value>
                <value>
                    <fullName>LA Valley</fullName>
                </value>
                <value>
                    <fullName>Long Beach/Pasadena</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Area</label>
    <nameField>
        <label>Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>AssignmentRegion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment Region</label>
        <referenceTo>Area__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>TEXT(AssignmentRegion__r.Region__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Healthcare_Provider__c.object
<CustomObject>
    <fields>
        <fullName>AreaCode__c</fullName>
        <formula>Contact__r.AreaCodePhone__c</formula>
        <label>Area Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AreaRegion__c</fullName>
        <formula>TEXT(Contact__r.Region__c)</formula>
        <label>Area Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Area__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Area</label>
        <referenceTo>Area__c</referenceTo>
        <relationshipLabel>Healthcare Providers</relationshipLabel>
        <relationshipName>Healthcare_Providers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Other_Healthcare_Providers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Previous, but inactive treaters on the case</description>
        <inlineHelpText>Designate a Healthcare Provider as inactive when the Employee is no longer treating with them</inlineHelpText>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <formula>Contact__r.Phone</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Primary</description>
        <inlineHelpText>Only one physician can be designated as Primary Health Care Provider.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProviderStatus__c</fullName>
        <label>Provider Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Bakersfield Area</fullName>
                </value>
                <value>
                    <fullName>Fresno North &amp; South</fullName>
                </value>
                <value>
                    <fullName>Imperial County</fullName>
                </value>
                <value>
                    <fullName>Inland Empire-Central</fullName>
                </value>
                <value>
                    <fullName>Inland Empire-South</fullName>
                </value>
                <value>
                    <fullName>LA Central</fullName>
                </value>
                <value>
                    <fullName>LA Southbay</fullName>
                </value>
                <value>
                    <fullName>LA Southeast</fullName>
                </value>
                <value>
                    <fullName>LA Valley</fullName>
                </value>
                <value>
                    <fullName>Long Beach/Pasadena</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>Oakland/East Bay</fullName>
                </value>
                <value>
                    <fullName>OC North</fullName>
                </value>
                <value>
                    <fullName>OC South</fullName>
                </value>
                <value>
                    <fullName>Sacto Central</fullName>
                </value>
                <value>
                    <fullName>Sacto North</fullName>
                </value>
                <value>
                    <fullName>SanGabriel Valley</fullName>
                </value>
                <value>
                    <fullName>San Jose &amp; South</fullName>
                </value>
                <value>
                    <fullName>Santa Barbara+North</fullName>
                </value>
                <value>
                    <fullName>SD Area North</fullName>
                </value>
                <value>
                    <fullName>SD Area South</fullName>
                </value>
                <value>
                    <fullName>SF Central &amp; North</fullName>
                </value>
                <value>
                    <fullName>SF South</fullName>
                </value>
                <value>
                    <fullName>Ventura/Oxnard Area</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Healthcare Provider</label>
    <nameField>
        <displayFormat>HP-{000000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Healthcare Providers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/HealthcareProviderTrgHandler.cls
public with sharing class HealthcareProviderTrgHandler 
{
	public static void onBeforeUpdate(Healthcare_Provider__c[] trgNew)
	{
		Set<String> areaCodeSet = new Set<String>();
		List<Case> caseUpdateList = new List<Case>();
		List<Healthcare_Provider__c> activePrimaryList = new List<Healthcare_Provider__c>();
		for(Healthcare_Provider__c hcp : trgNew)
		{
			//if(!hcp.Inactive__c && hcp.Primary__c)
			if(hcp.ProviderStatus__c=='Active' && hcp.Primary__c)
			{
				//areaCodeSet.add(cleanPhone(hcp.Phone__c).subString(0,3));
				System.debug('AREACODE::::::::::'+hcp.AreaCode__c);
				areaCodeSet.add(hcp.AreaCode__c);
				activePrimaryList.add(hcp);
			}
		}			
		if(areaCodeSet.size()>0)
		{
			Map<String,List<Area__c>> areaByZip = new Map<String,List<Area__c>>();
			for(Area__c area : [SELECT Id, Name, Region__c FROM Area__c where Name in :areaCodeSet])
			{
				if(!areaByZip.containsKey(area.Name))
					areaByZip.put(area.Name,new List<Area__c>());
				areaByZip.get(area.Name).add(area);
			}
				
			for(Healthcare_Provider__c hcp : activePrimaryList)
			{
				//if(areaByZip.containsKey(cleanPhone(hcp.Phone__c).subString(0,3)))
				if(areaByZip.containsKey(hcp.AreaCode__c))
				{
					//for(Area__c area : areaByZip.get(cleanPhone(hcp.Phone__c).subString(0,3)))
					for(Area__c area : areaByZip.get(hcp.AreaCode__c))
					{
						if(area.Region__c==hcp.AreaRegion__c)
						{
							hcp.Area__c = area.Id;
							Case c = new Case(Id=hcp.Case__c,AssignmentRegion__c=hcp.Area__c);
							caseUpdateList.add(c);
						}
					}
				}
			}
		}
		if(caseUpdateList.size()>0)
			update caseUpdateList;
	}
	public static void onBeforeInsert(Healthcare_Provider__c[] trgNew)
	{
		Set<String> areaCodeSet = new Set<String>();
		List<Case> caseUpdateList = new List<Case>();
		List<Healthcare_Provider__c> activePrimaryList = new List<Healthcare_Provider__c>();
		for(Healthcare_Provider__c hcp : trgNew)
		{
			//if(!hcp.Inactive__c && hcp.Primary__c)
			if(hcp.ProviderStatus__c=='Active' && hcp.Primary__c)
			{
				//areaCodeSet.add(cleanPhone(hcp.Phone__c).subString(0,3));
				System.debug('AREACODE2::::::::::'+hcp.AreaCode__c);
				areaCodeSet.add(hcp.AreaCode__c);
				activePrimaryList.add(hcp);
			}
		}			
		Map<String,List<Area__c>> areaByZip = new Map<String,List<Area__c>>();
		for(Area__c area : [SELECT Id, Name, Region__c FROM Area__c where Name in :areaCodeSet])
		{
			if(!areaByZip.containsKey(area.Name))
				areaByZip.put(area.Name,new List<Area__c>());
			areaByZip.get(area.Name).add(area);
		}
			
		for(Healthcare_Provider__c hcp : activePrimaryList)
		{
			//if(areaByZip.containsKey(cleanPhone(hcp.Phone__c).subString(0,3)))
			if(areaByZip.containsKey(hcp.AreaCode__c))
			{
				//for(Area__c area : areaByZip.get(cleanPhone(hcp.Phone__c).subString(0,3)))
				for(Area__c area : areaByZip.get(hcp.AreaCode__c))
				{
					if(area.Region__c==hcp.AreaRegion__c)
					{
						hcp.Area__c = area.Id;
						Case c = new Case(Id=hcp.Case__c,AssignmentRegion__c=hcp.Area__c);
						caseUpdateList.add(c);
					}
				}
			}
		}
		if(caseUpdateList.size()>0)
			update caseUpdateList;
	}
	/*private static String cleanPhone(String phoneNumber)
	{
		String digits;
		Pattern nonDigits = Pattern.compile('[^0-9]');
		Matcher matchDigits = nonDigits.matcher(phoneNumber);
		digits = matchDigits.replaceAll('');
		if(digits.length()!=10)
			return phoneNumber;
		return digits;
	}*/
}