src/objects/Area__c.object
<CustomObject>
    <fields>
        <fullName>AreaNumber__c</fullName>
        <label>Area</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AssignedCaseManagers__c</fullName>
        <label>Assigned Case Manager(s)</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Area</label>
    <nameField>
        <label>Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>AreaNumber__c</fullName>
        <formula>TEXT(AssignmentRegion__r.AreaNumber__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Area</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AssignmentRegion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment Region</label>
        <referenceTo>Area__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Diagnosis__c</fullName>
        <description>Current Diagnosis</description>
        <inlineHelpText>If more than three diagnoses, list as 1. 2. 3. 4. etc.

For one to three diagnoses, write as narrative.</inlineHelpText>
        <label>Current Diagnosis</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Employee_Case_Trakker__c</fullName>
        <label>Employee (Case Trakker)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Jurisdiction__c</fullName>
        <description>State where the file is being managed.</description>
        <inlineHelpText>Select the State where the File is being managed.</inlineHelpText>
        <label>Jurisdiction</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>California-WC</fullName>
                </value>
                <value>
                    <fullName>Nevada-WC</fullName>
                </value>
                <value>
                    <fullName>New Mexico-WC</fullName>
                </value>
                <value>
                    <fullName>Arizona-WC</fullName>
                </value>
                <value>
                    <fullName>Educational Services</fullName>
                </value>
                <value>
                    <fullName>Ergo. Eval.</fullName>
                </value>
                <value>
                    <fullName>LCP</fullName>
                </value>
                <value>
                    <fullName>LMS</fullName>
                </value>
                <value>
                    <fullName>EWT</fullName>
                </value>
                <value>
                    <fullName>Seminars</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Nature_and_History_of_Injury__c</fullName>
        <description>Nature &amp; History of Injury</description>
        <inlineHelpText>Include mechanism of Injury, date of injury, and initial symptoms.</inlineHelpText>
        <label>Nature &amp; History of Injury</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>QB_Service_Item__c</fullName>
        <description>QB Service Item</description>
        <label>QB Service Item</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ER</fullName>
                </value>
                <value>
                    <fullName>Ergo. Eval.</fullName>
                </value>
                <value>
                    <fullName>Interactive Process</fullName>
                </value>
                <value>
                    <fullName>EWT</fullName>
                </value>
                <value>
                    <fullName>Expenses</fullName>
                </value>
                <value>
                    <fullName>Job Analysis</fullName>
                </value>
                <value>
                    <fullName>LCP</fullName>
                </value>
                <value>
                    <fullName>LMS</fullName>
                </value>
                <value>
                    <fullName>Longshore-Voc</fullName>
                </value>
                <value>
                    <fullName>LTD</fullName>
                </value>
                <value>
                    <fullName>MCM-CAT</fullName>
                </value>
                <value>
                    <fullName>MCM-On Site</fullName>
                </value>
                <value>
                    <fullName>MCM-Tele</fullName>
                </value>
                <value>
                    <fullName>Mileage</fullName>
                </value>
                <value>
                    <fullName>Seminars</fullName>
                </value>
                <value>
                    <fullName>Soc. Service</fullName>
                </value>
                <value>
                    <fullName>TCM Triage</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Travel/Wait</fullName>
                </value>
                <value>
                    <fullName>VRC</fullName>
                </value>
                <value>
                    <fullName>Discount</fullName>
                </value>
                <value>
                    <fullName>RUSH-MCM-On Site</fullName>
                </value>
                <value>
                    <fullName>RUSH-Mileage</fullName>
                </value>
                <value>
                    <fullName>RUSH-Travel/Wait</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Specialty__c</fullName>
        <label>Specialty</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supervised_by__c</fullName>
        <description>Supervised by</description>
        <label>Supervised by</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Denise Demianeau, RN, CCM</fullName>
                </value>
                <value>
                    <fullName>Catherine Kvasnicka, RN, MSN</fullName>
                </value>
                <value>
                    <fullName>Tanya Jutting-Loumakis, MA, CCM</fullName>
                </value>
                <value>
                    <fullName>Diane Campos, General Manager</fullName>
                </value>
                <value>
                    <fullName>Alysha Calderon</fullName>
                </value>
                <value>
                    <fullName>Senior Mentor</fullName>
                </value>
                <value>
                    <fullName>Angie Jung, RN, BSN, CRRN, CCM</fullName>
                </value>
                <value>
                    <fullName>Contractor - Not Applicable</fullName>
                </value>
                <value>
                    <fullName>Whitney Boyles, RN, BSN, MS, CCM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Healthcare_Provider__c.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Area</label>
        <referenceTo>Area__c</referenceTo>
        <relationshipLabel>Healthcare Providers</relationshipLabel>
        <relationshipName>Healthcare_Providers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Other_Healthcare_Providers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Primary</description>
        <inlineHelpText>Only one physician can be designated as Primary Health Care Provider.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProviderStatus__c</fullName>
        <label>Provider Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Specialty__c</fullName>
        <description>Specialty</description>
        <inlineHelpText>Specialty of healthcare provider</inlineHelpText>
        <label>Specialty</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Healthcare Provider</label>
    <nameField>
        <displayFormat>HP-{000000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Healthcare Providers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Surgery_Hospitalization__c.object
<CustomObject>
    <fields>
        <fullName>Admission_Date__c</fullName>
        <description>Admission Date</description>
        <inlineHelpText>Select Date</inlineHelpText>
        <label>Admission Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <description>Case</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Surgeries / Hospitalizations</relationshipLabel>
        <relationshipName>Surgeries_Hospitalizations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Surgery / Hospitalization</label>
    <nameField>
        <displayFormat>SH-{00000}</displayFormat>
        <label>Surgery / Hospitalization Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surgeries / Hospitalizations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestCaseReOpen.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestCaseReOpen 
{
    static Case c;
    static testMethod void myUnitTest() 
    {
        CaseReOpen reOpen = new CaseReOpen(new ApexPages.StandardController(c));
        reOpen.reOpenCase();
    }
    static
    {
    	Area__c area = new Area__c();
    	area.Name='706';
    	area.AreaNumber__c='1';
    	area.AssignedCaseManagers__c='Jim Tom; Billy Bob;';
    	insert area;
    	
    	c = new Case();
        c.Supervised_by__c = 'MySelf';
        c.Status = 'Closed';
        c.QB_Service_Item__c = 'ER';
        c.Priority = 'High';
        c.Origin = 'Web';
        c.Nature_and_History_of_Injury__c = 'Nothing';
        c.Employee_Case_Trakker__c = 'Nothing';
        c.Current_Diagnosis__c = 'Fine';
        c.Jurisdiction__c = 'California-WC';
        c.QB_Service_Item__c = 'MCM-On Site';
        c.AssignmentRegion__c = area.Id;
        insert c;
        
        Surgery_Hospitalization__c sh = new Surgery_Hospitalization__c();
        sh.Case__c = c.Id;
        sh.Admission_Date__c=Date.today();        
        insert sh;
        
        Healthcare_Provider__c hcp = new Healthcare_Provider__c();
        hcp.Area__c=area.Id;
        hcp.Case__c=c.Id;
        hcp.Primary__c=true;
        hcp.ProviderStatus__c='Active';
        hcp.Specialty__c='Awesomeness';
        insert hcp;
    }
}