src/objects/Area__c.object
<CustomObject>
    <fields>
        <fullName>AreaNumber__c</fullName>
        <label>Area</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <defaultValue>&apos;a&apos;</defaultValue>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Area</label>
    <nameField>
        <label>Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>AreaNumber__c</fullName>
        <formula>TEXT(AssignmentRegion__r.AreaNumber__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Area</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AssignmentRegion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment Region</label>
        <referenceTo>Area__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Employee</description>
        <label>Employee</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Open Files (Cases)</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TotalProfessionalHoursA__c</fullName>
        <label>Total Professional Hours (A)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalProfessionalHoursB__c</fullName>
        <label>Total Professional Hours (B)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Note_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Adj_Expenses__c</fullName>
        <description>Adj. Expenses</description>
        <label>Adj. Expenses</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Adj_Mileage__c</fullName>
        <description>Adj. Mileage</description>
        <label>Adj. Mileage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Adj_Professional_Hours__c</fullName>
        <description>Adj. Professional Hours</description>
        <inlineHelpText>Audit: Invoice Time to QB</inlineHelpText>
        <label>Adj. Professional Hours</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Adj_Travel_Wait_Hours__c</fullName>
        <description>Adj. Travel/Wait Hours</description>
        <inlineHelpText>Audit:  Invoice Non-Professional Time to QB</inlineHelpText>
        <label>Adj. Travel/Wait Hours</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Covering_Nurse__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Covering Nurse</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Expenses_Nurse__c</fullName>
        <label>Expenses (Nurse)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expenses__c</fullName>
        <description>Expenses</description>
        <label>Expenses</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Mileage_Nurse__c</fullName>
        <label>Mileage (Nurse)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Mileage__c</fullName>
        <description>Mileage</description>
        <label>Mileage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Primary_Nurse__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Nurse</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Professional_Hours_Nurse__c</fullName>
        <label>Professional Hours (Nurse)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Professional_Hours__c</fullName>
        <description>Professional Hours</description>
        <inlineHelpText>Edit : Nurse Professional Time to QB</inlineHelpText>
        <label>Professional Units</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Report__c</fullName>
        <description>Report</description>
        <inlineHelpText>Case Report that Entry is related to</inlineHelpText>
        <label>Report</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Case Note Entries</relationshipLabel>
        <relationshipName>Case_Note_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Travel_Wait_Hours_Nurse__c</fullName>
        <label>Travel/Wait Hours (Nurse)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Travel_Wait_Hours__c</fullName>
        <description>Travel/Wait Hours</description>
        <inlineHelpText>Edit:  Nurse Non-Professional Time to QB</inlineHelpText>
        <label>Travel/Wait Units</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>Case Note Entry</label>
    <nameField>
        <displayFormat>Bill-{00000}</displayFormat>
        <label>Case Note Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Note Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CMMetric__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <label>Employee</label>
        <referenceTo>SFDC_Employee__c</referenceTo>
        <relationshipLabel>CM Metrics</relationshipLabel>
        <relationshipName>CM_Metrics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>56</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TotalExpensesNurse__c</fullName>
        <label>Total Expenses (Nurse)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalMileageA__c</fullName>
        <label>Total Mileage (A)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalMileageB__c</fullName>
        <label>Total Mileage (B)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalMileageNurse__c</fullName>
        <label>Total Mileage (Nurse)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalProfessionalHoursA__c</fullName>
        <label>Total Professional Hours (A)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalProfessionalHoursB__c</fullName>
        <label>Total Professional Hours (B)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalProfessionalHoursNurse__c</fullName>
        <label>Total Professional Hours (Nurse)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalTravelWaitHoursA__c</fullName>
        <label>Total Travel/Wait Hours (A)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalTravelWaitHoursB__c</fullName>
        <label>Total Travel/Wait Hours (B)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalTravelWaitHoursNurse__c</fullName>
        <label>Total Travel/Wait Hours (Nurse)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>CM Metric</label>
    <nameField>
        <displayFormat>CMMID-{0000000000}</displayFormat>
        <label>CM Metric ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CM Metrics</pluralLabel>
    <recordTypes>
        <fullName>AreaMetric</fullName>
        <active>true</active>
        <label>Area Metric</label>
    </recordTypes>
    <recordTypes>
        <fullName>UserMetric</fullName>
        <active>true</active>
        <label>User Metric</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CMMetricsDateRange__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom Setting to set date ranges for CM Metric calculations.</description>
    <fields>
        <fullName>EndDate__c</fullName>
        <inlineHelpText>End Date for calculations to take place.  Leave Blank for default dates to be active.</inlineHelpText>
        <label>EndDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <inlineHelpText>StartDate of Calculations.  Leave Blank for default values to be active.</inlineHelpText>
        <label>StartDate</label>
        <type>Date</type>
    </fields>
    <label>CMMetricsDateRange</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>A_Note_Approval_Date_Time__c</fullName>
        <description>A Note Approval Date / Time</description>
        <label>A Note Approval Date / Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lookup Employee associated to the Report</inlineHelpText>
        <label>Employee</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Case_Reports_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Reports</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Report_Submission_Date__c</fullName>
        <description>Report Submission Date</description>
        <label>Report Submission Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/SFDC_Employee__c.object
<CustomObject>
    <fields>
        <fullName>SF_Username__c</fullName>
        <externalId>true</externalId>
        <label>SF Username</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchCaseNoteEntryMetrics.cls
global class BatchCaseNoteEntryMetrics implements Database.Batchable<sObject>, Database.Stateful
{
	Date runDate = Date.today();
	integer daysInMonth = Date.daysInMonth(runDate.year(),runDate.month());
	Date metricDate = Date.parse(String.valueOf(runDate.month())+'/'+daysInMonth+'/'+runDate.year());
	Map<String,CMMetric__c> keyMap = new Map<String, CMMetric__c>();
	String monthYear = '';	
	Map<String,Id> rtIdMap = new Map<String,Id>();
	
	global BatchCaseNoteEntryMetrics()
	{
		for(RecordType rt : [SELECT Id,DeveloperName FROM RecordType WHERE SobjectType='CMMetric__c'])
			rtIdMap.put(rt.DeveloperName,rt.Id);
	}
	global Database.Querylocator start(Database.Batchablecontext BC)
    {
    	/*OLD VERSION
    	return Database.getQueryLocator([SELECT Primary_Nurse__c,Covering_Nurse__c,Adj_Travel_Wait_Hours__c,Adj_Professional_Hours__c,Adj_Mileage__c,
                                         Adj_Expenses__c,CreatedById,CreatedBy.UserName,Report__r.Related_Case__r.AssignmentRegion__r.AreaNumber__c,
                                         Report__c,Travel_Wait_Hours__c,Travel_Wait_Hours_Nurse__c,Professional_Hours__c,Professional_Hours_Nurse__c,
                                         Mileage__c,Mileage_Nurse__c,Expenses__c,Expenses_Nurse__c,Report__r.Report_Submission_Date__c 
                                         FROM Case_Note_Entry__c WHERE Report__r.StageName in ('Approved','Completed')
                                         AND Report__r.Report_Submission_Date__c > 2008-12-31 AND Report__r.A_Note_Approval_Date_Time__c > 2008-12-31T00:00:00.000Z 
                                         AND CreatedBy.IsActive=true AND (Primary_Nurse__c=true OR Covering_Nurse__c=true)]);
    	*/

    	/* Updates made by Corrao Group (Jonathan Castelo) January 2018
    		Updated Filter on Query getQueryLocator
    		Enabled Custom Setting for Start and End Date Range
    		Default Value of Dates to be set when Custom Setting values are Blank
    		Custom Setting values are used to calculate metrics in past and defaults are for current
    		Remove IsActive check on creating User.

		*/

    		//GET DATE RANGES FROM CUSTOM SETTING OR USE DEFAULTS 
    		CMMetricsDateRange__c dateRange = CMMetricsDateRange__c.getOrgDefaults();
    		Date sDate;
    		Date eDate;

    		if(dateRange.StartDate__c == null){
    			//Build Date for First Day of the Month
    			sDate = Date.newInstance(System.today().addDays(-90).year(),System.today().addDays(-90).month(),1);
    		}
    		else{
    			sDate = Date.newInstance(dateRange.StartDate__c.year(),dateRange.StartDate__c.month(),1);
    		}

			//Build Date for Last Day of the Month
    		if(dateRange.EndDate__c == null)
    			eDate = System.today();
    		else{
    			eDate = Date.newInstance(dateRange.EndDate__c.year(),
    											dateRange.EndDate__c.Month() + 1, 
    												Date.daysInMonth(dateRange.EndDate__c.year(),dateRange.EndDate__c.Month()));
    		}

    		return Database.getQueryLocator([SELECT Primary_Nurse__c,Covering_Nurse__c,Adj_Travel_Wait_Hours__c,Adj_Professional_Hours__c,Adj_Mileage__c,
                                         Adj_Expenses__c,CreatedById,CreatedBy.UserName,Report__r.Related_Case__r.AssignmentRegion__r.AreaNumber__c,
                                         Report__c,Travel_Wait_Hours__c,Travel_Wait_Hours_Nurse__c,Professional_Hours__c,Professional_Hours_Nurse__c,
                                         Mileage__c,Mileage_Nurse__c,Expenses__c,Expenses_Nurse__c,Report__r.Report_Submission_Date__c 
                                         FROM Case_Note_Entry__c 
                                         WHERE Report__r.StageName in ('Approved','Completed')
                                         AND Report__r.Report_Submission_Date__c >=: sDate AND  Report__r.Report_Submission_Date__c <=: eDate
                                         //AND Report__r.A_Note_Approval_Date_Time__c >=: sDate AND Report__r.A_Note_Approval_Date_Time__c <: eDate.addDays(90)
                                         AND Report__r.A_Note_Approval_Date_Time__c != null
                                         AND (Primary_Nurse__c=true OR Covering_Nurse__c=true)]);
    


    }
    global void execute(Database.Batchablecontext BC, list<SObject> scope)
    {
    	try{
    	String areaKey;
    	String userKey;
    	CMMetric__c areaMetric;
    	CMMetric__c userMetric;
    	for(Sobject so : scope)
    	{
    		//report submission date is used to tie into case metric (cannot be null in SOQL)
    		//bnotesapprovaldatetime - has to be populated(cannot be null in SOQL)
    		//Submitted or Approved (not completed anymore)
    		areaMetric = null;
    		userMetric = null;
    		areaKey = null;
    		userKey = null;
    		Case_Note_Entry__c cne = (Case_Note_Entry__c)so;
    		monthYear = String.valueOf(cne.Report__r.Report_Submission_Date__c.month()+'/'+cne.Report__r.Report_Submission_Date__c.year());
    		if(cne.Report__r.Related_Case__r.AssignmentRegion__r.AreaNumber__c!=null&&cne.Report__r.Related_Case__r.AssignmentRegion__r.AreaNumber__c!='')
    			areaKey = cne.Report__r.Related_Case__r.AssignmentRegion__r.AreaNumber__c+':'+cne.CreatedById+':'+monthYear;
    		userKey = cne.CreatedById+':'+monthYear;

    		//key = cne.Report__r.Related_Case__r.AssignmentRegion__r.AreaNumber__c+':'+cne.CreatedById+':'+monthYear;
    		daysInMonth = Date.daysInMonth(cne.Report__r.Report_Submission_Date__c.year(),cne.Report__r.Report_Submission_Date__c.month());
    		metricDate = Date.parse(String.valueOf(cne.Report__r.Report_Submission_Date__c.month())+'/'+daysInMonth+'/'+cne.Report__r.Report_Submission_Date__c.year());

    		SFDC_Employee__c emp = new SFDC_Employee__c();
    		
    		//Check for Sandbox ".Implement"
	   		if(cne.CreatedBy.Username.contains('.implement'))
	   			emp.SF_Username__c = cne.CreatedBy.UserName.remove('.implement');
	   		else
	   			emp.SF_Username__c = cne.CreatedBy.UserName;
    				




    		if(areaKey!=null)
    		{
    			if(!keyMap.containsKey(areaKey))
    				keyMap.put(areaKey, new CMMetric__c(ExternalId__c=areaKey,TotalTravelWaitHoursNurse__c=0,TotalTravelWaitHoursB__c=0,
    					TotalTravelWaitHoursA__c=0,TotalProfessionalHoursNurse__c=0,TotalProfessionalHoursB__c=0,TotalProfessionalHoursA__c=0,
    					TotalMileageNurse__c=0,TotalMileageB__c=0,TotalMileageA__c=0,TotalExpensesNurse__c=0,TotalExpensesB__c=0,TotalExpensesA__c=0,
    					Employee__r=emp,Area__c=cne.Report__r.Related_Case__r.AssignmentRegion__r.AreaNumber__c,
    					MetricDate__c=metricDate,TotalExpensesCA__c=0,TotalExpensesCB__c=0,TotalExpensesCNurse__c=0,TotalMileageCA__c=0,
    					TotalMileageCB__c=0,TotalMileageCNurse__c=0,TotalProfessionalHoursCA__c=0,TotalProfessionalHoursCB__c=0,
    					TotalProfessionalHoursCNurse__c=0,TotalTravelWaitHoursCA__c=0,TotalTravelWaitHoursCB__c=0,TotalTravelWaitHoursCNurse__c=0,
    					RecordTypeId=rtIdMap.get('AreaMetric')));

					System.debug('metricDate ' + metricDate + ' area ' + metricDate);
    		}
    		if(!keyMap.containsKey(userKey))
    			keyMap.put(userKey, new CMMetric__c(ExternalId__c=userKey,TotalTravelWaitHoursNurse__c=0,TotalTravelWaitHoursB__c=0,TotalTravelWaitHoursA__c=0,TotalProfessionalHoursNurse__c=0,TotalProfessionalHoursB__c=0,TotalProfessionalHoursA__c=0,TotalMileageNurse__c=0,TotalMileageB__c=0,TotalMileageA__c=0,TotalExpensesNurse__c=0,TotalExpensesB__c=0,TotalExpensesA__c=0,Employee__r=emp,MetricDate__c=metricDate,TotalExpensesCA__c=0,TotalExpensesCB__c=0,TotalExpensesCNurse__c=0,TotalMileageCA__c=0,TotalMileageCB__c=0,TotalMileageCNurse__c=0,TotalProfessionalHoursCA__c=0,TotalProfessionalHoursCB__c=0,TotalProfessionalHoursCNurse__c=0,TotalTravelWaitHoursCA__c=0,TotalTravelWaitHoursCB__c=0,TotalTravelWaitHoursCNurse__c=0,RecordTypeId=rtIdMap.get('UserMetric')));
				System.debug('metricDate ' + metricDate + ' user');

    		if(keyMap.containsKey(areaKey))
    			areaMetric = keyMap.get(areaKey);
    		userMetric = keyMap.get(userKey);
    		
    		if(cne.Primary_Nurse__c)
    		{
	    		if(cne.Travel_Wait_Hours_Nurse__c!=null)
	    		{
	    			if(areaMetric!=null)
	    				areaMetric.TotalTravelWaitHoursNurse__c+=cne.Travel_Wait_Hours_Nurse__c;
	    			userMetric.TotalTravelWaitHoursNurse__c+=cne.Travel_Wait_Hours_Nurse__c;
	    		}
	    		if(cne.Professional_Hours_Nurse__c!=null)
    			{
	    			if(areaMetric!=null)
	    				areaMetric.TotalProfessionalHoursNurse__c+=cne.Professional_Hours_Nurse__c;
	    			userMetric.TotalProfessionalHoursNurse__c+=cne.Professional_Hours_Nurse__c;
    			}
	    		if(cne.Mileage_Nurse__c!=null)
	    		{
	    			if(areaMetric!=null)
	    				areaMetric.TotalMileageNurse__c+=cne.Mileage_Nurse__c;
	    			userMetric.TotalMileageNurse__c+=cne.Mileage_Nurse__c;
	    		}
	    		if(cne.Expenses_Nurse__c!=null)
	    		{
	    			if(areaMetric!=null)
	    				areaMetric.TotalExpensesNurse__c+=cne.Expenses_Nurse__c;
	    			userMetric.TotalExpensesNurse__c+=cne.Expenses_Nurse__c;
	    		}
	    		
	    		if(cne.Travel_Wait_Hours__c!=null)
	    		{
		    		if(areaMetric!=null)
	    				areaMetric.TotalTravelWaitHoursA__c+=cne.Travel_Wait_Hours__c;
	    			userMetric.TotalTravelWaitHoursA__c+=cne.Travel_Wait_Hours__c;
	    		}	    		
		    	if(cne.Professional_Hours__c!=null)
		    	{
	    			if(areaMetric!=null)
	    				areaMetric.TotalProfessionalHoursA__c+=cne.Professional_Hours__c;
	    			userMetric.TotalProfessionalHoursA__c+=cne.Professional_Hours__c;
		    	}
	    		if(cne.Mileage__c!=null)
	    		{
	    			if(areaMetric!=null)
	    				areaMetric.TotalMileageA__c+=cne.Mileage__c;
	    			userMetric.TotalMileageA__c+=cne.Mileage__c;
	    		}
	    		if(cne.Expenses__c!=null)
	    		{
	    			if(areaMetric!=null)
	    				areaMetric.TotalExpensesA__c+=cne.Expenses__c;
	    			userMetric.TotalExpensesA__c+=cne.Expenses__c;
	    		}
	    		
	    		if(cne.Adj_Travel_Wait_Hours__c!=null)
	    		{
	    			if(areaMetric!=null)
	    				areaMetric.TotalTravelWaitHoursB__c+=cne.Adj_Travel_Wait_Hours__c;
	    			userMetric.TotalTravelWaitHoursB__c+=cne.Adj_Travel_Wait_Hours__c;
	    		}
	    		if(cne.Adj_Professional_Hours__c!=null)
	    		{    		
	    			if(areaMetric!=null)
	    				areaMetric.TotalProfessionalHoursB__c+=cne.Adj_Professional_Hours__c;
	    			userMetric.TotalProfessionalHoursB__c+=cne.Adj_Professional_Hours__c;
	    		}
	    		if(cne.Adj_Mileage__c!=null)
	    		{
	    			if(areaMetric!=null)
	    				areaMetric.TotalMileageB__c+=cne.Adj_Mileage__c;
	    			userMetric.TotalMileageB__c+=cne.Adj_Mileage__c;
	    		}
	    		if(cne.Adj_Expenses__c!=null)
	    		{
	    			if(areaMetric!=null)
	    				areaMetric.TotalExpensesB__c+=cne.Adj_Expenses__c;
	    			userMetric.TotalExpensesB__c+=cne.Adj_Expenses__c;
	    		}
    		}
    		if(cne.Covering_Nurse__c)
    		{
    			if(cne.Travel_Wait_Hours_Nurse__c!=null)
    			{
	    			if(areaMetric!=null)
	    				areaMetric.TotalTravelWaitHoursCNurse__c+=cne.Travel_Wait_Hours_Nurse__c;
	    			userMetric.TotalTravelWaitHoursCNurse__c+=cne.Travel_Wait_Hours_Nurse__c;
    			}
	    		if(cne.Professional_Hours_Nurse__c!=null)
	    		{
	    			if(areaMetric!=null)
	    				areaMetric.TotalProfessionalHoursCNurse__c+=cne.Professional_Hours_Nurse__c;
	    			userMetric.TotalProfessionalHoursCNurse__c+=cne.Professional_Hours_Nurse__c;
	    		}
	    		if(cne.Mileage_Nurse__c!=null)
	    		{
	    			if(areaMetric!=null)
	    				areaMetric.TotalMileageCNurse__c+=cne.Mileage_Nurse__c;
	    			userMetric.TotalMileageCNurse__c+=cne.Mileage_Nurse__c;
	    		}
	    		if(cne.Expenses_Nurse__c!=null)
	    		{
	    			if(areaMetric!=null)
	    				areaMetric.TotalExpensesCNurse__c+=cne.Expenses_Nurse__c;
	    			userMetric.TotalExpensesCNurse__c+=cne.Expenses_Nurse__c;
	    		}
	    		
	    		if(cne.Travel_Wait_Hours__c!=null)
	    		{
		    		if(areaMetric!=null)
	    				areaMetric.TotalTravelWaitHoursCA__c+=cne.Travel_Wait_Hours__c;
	    			userMetric.TotalTravelWaitHoursCA__c+=cne.Travel_Wait_Hours__c;
	    		}	    		
		    	if(cne.Professional_Hours__c!=null)
		    	{
	    			if(areaMetric!=null)
	    				areaMetric.TotalProfessionalHoursCA__c+=cne.Professional_Hours__c;
	    			userMetric.TotalProfessionalHoursCA__c+=cne.Professional_Hours__c;
		    	}
	    		if(cne.Mileage__c!=null)
	    		{
	    			if(areaMetric!=null)
	    				areaMetric.TotalMileageCA__c+=cne.Mileage__c;
	    			userMetric.TotalMileageCA__c+=cne.Mileage__c;
	    		}
	    		if(cne.Expenses__c!=null)
	    		{
	    			if(areaMetric!=null)
	    				areaMetric.TotalExpensesCA__c+=cne.Expenses__c;
	    			userMetric.TotalExpensesCA__c+=cne.Expenses__c;
	    		}
	    		
	    		if(cne.Adj_Travel_Wait_Hours__c!=null)
	    		{
	    			if(areaMetric!=null)
	    				areaMetric.TotalTravelWaitHoursCB__c+=cne.Adj_Travel_Wait_Hours__c;
	    			userMetric.TotalTravelWaitHoursCB__c+=cne.Adj_Travel_Wait_Hours__c;
	    		}
	    		if(cne.Adj_Professional_Hours__c!=null)
	    		{    		
	    			if(areaMetric!=null)
	    				areaMetric.TotalProfessionalHoursCB__c+=cne.Adj_Professional_Hours__c;
	    			userMetric.TotalProfessionalHoursCB__c+=cne.Adj_Professional_Hours__c;
	    		}
	    		if(cne.Adj_Mileage__c!=null)
	    		{
	    			if(areaMetric!=null)
	    				areaMetric.TotalMileageCB__c+=cne.Adj_Mileage__c;
	    			userMetric.TotalMileageCB__c+=cne.Adj_Mileage__c;
	    		}
	    		if(cne.Adj_Expenses__c!=null)
	    		{
	    			if(areaMetric!=null)
	    				areaMetric.TotalExpensesCB__c+=cne.Adj_Expenses__c;
	    			userMetric.TotalExpensesCB__c+=cne.Adj_Expenses__c;
	    		}
    		} 		
    	}
    	}
    	catch(Exception e){

			Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
			String[] toAddresses = new String[] {'support@isyscm.com'};
			mail.setToAddresses(toAddresses);
			mail.setSubject('Error Processing BatchCaseNoteEntryMetrics');
			mail.setPlainTextBody
			('The BatchCaseNoteEntryMetrics job failed. Some records may have been processed:' + '\n' + 'Message: ' + e.getMessage() + '\nStackTrace: ' + e.getStackTraceString() + '');
			Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
			
		}
    }
    global void finish (Database.Batchablecontext BC)
    {
    	upsert keyMap.values() ExternalId__c;
    }
}