src/objects/Billing_Code__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DefaultCode__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DefaultCode</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Max__c</fullName>
        <label>Max</label>
        <precision>3</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Min__c</fullName>
        <label>Min</label>
        <precision>3</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>Billing Code</label>
    <nameField>
        <label>Billing Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Employee_Case_Trakker__c</fullName>
        <label>Employee (Case Trakker)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Note_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Adj_Travel_Wait_Hours__c</fullName>
        <description>Adj. Travel/Wait Hours</description>
        <inlineHelpText>Audit:  Invoice Non-Professional Time to QB</inlineHelpText>
        <label>Adj. Travel/Wait Hours</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Billing_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Billing Code</description>
        <label>Billing Code</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>INACTIVE AS OF STAFF MEETING (8/6/11)</errorMessage>
            <filterItems>
                <field>Billing_Code__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Billing_Code__c</referenceTo>
        <relationshipLabel>Case Note Entries</relationshipLabel>
        <relationshipName>Case_Note_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Driving_From_City__c</fullName>
        <description>Driving From (City)</description>
        <label>Driving From (City)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Driving_To_City__c</fullName>
        <description>Driving To (City)</description>
        <label>Driving To (City)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mileage_Nurse__c</fullName>
        <label>Mileage (Nurse)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Report__c</fullName>
        <description>Report</description>
        <inlineHelpText>Case Report that Entry is related to</inlineHelpText>
        <label>Report</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Case Note Entries</relationshipLabel>
        <relationshipName>Case_Note_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Travel_Wait_Hours_Nurse__c</fullName>
        <label>Travel/Wait Hours (Nurse)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Work_Description__c</fullName>
        <description>Work Description</description>
        <inlineHelpText>Description of work being performed or recorded</inlineHelpText>
        <label>Work Description</label>
        <type>TextArea</type>
    </fields>
    <label>Case Note Entry</label>
    <nameField>
        <displayFormat>Bill-{00000}</displayFormat>
        <label>Case Note Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Note Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>P_S_Comment__c</fullName>
        <description>Assessment Comment</description>
        <inlineHelpText>Address current status, why they are approaching P&amp;S/S&amp;R/Stationary status or why they are not.</inlineHelpText>
        <label>Assessment Comment</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Related_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Reports</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Date_From__c</fullName>
        <description>Service Date From</description>
        <label>Service Date From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_Date_Thru__c</fullName>
        <description>Service Date Thru</description>
        <label>Service Date Thru</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CaseNoteRollupSyncTest.cls
@isTest
private class CaseNoteRollupSyncTest 
{    
    public static testMethod void testCaseNoteRollup() 
    {
        Account testAccount = new Account();
        testAccount.Name = 'Test';
        insert testAccount;
        
        Case testCase = new Case(Employee_Case_Trakker__c='Test');
        insert testCase;
        
        Opportunity testOpp = new Opportunity();
        testOpp.AccountId = testAccount.Id;
        testOpp.Name = 'Test - Opportunity';
        testOpp.StageName = 'Prospecting';
        testOpp.CloseDate = System.today();
        testOpp.P_S_Comment__c = 'Test';
        testOpp.Related_Case__c = testCase.Id;
        //testOpp.Service_Date_From__c = System.today() - 3;
        //testOpp.Service_Date_Thru__c = System.today();
        insert testOpp;
        
        List<Billing_Code__c> bcList = new List<Billing_Code__c>();
        Billing_Code__c proHoursBc = new Billing_Code__c();
        proHoursBc.Active__c = true;
        proHoursBc.Name = 'W';
        proHoursBc.Max__c = 10;
        proHoursBc.Min__c = 0;
        proHoursBc.DefaultCode__c = true;
        bcList.add(proHoursBc);
        
        Billing_Code__c travelWaitHoursBc = new Billing_Code__c();
        travelWaitHoursBc.Active__c = true;
        travelWaitHoursBc.Name = 'T';
        travelWaitHoursBc.Max__c = 10;
        travelWaitHoursBc.Min__c = 0;
        travelWaitHoursBc.DefaultCode__c = true;
        bcList.add(travelWaitHoursBc);
        insert bcList;
        
        Case_Note_Entry__c travelWaitCaseNote = new Case_Note_Entry__c();        
        travelWaitCaseNote.Adj_Travel_Wait_Hours__c = 1;        
        travelWaitCaseNote.Travel_Wait_Hours_Nurse__c = 1;     
        travelWaitCaseNote.Mileage_Nurse__c = 1;
        travelWaitCaseNote.Driving_From_City__c = 'Dallas';
        travelWaitCaseNote.Driving_To_City__c='Houston';
        travelWaitCaseNote.Work_Description__c = 'Test';
        travelWaitCaseNote.Billing_Code__c = travelWaitHoursBc.Id;       
        travelWaitCaseNote.Report__c = testOpp.Id; 
        insert travelWaitCaseNote;
        
        Test.startTest();        
        testOpp.StageName = 'Submitted';
        update testOpp;        
        Test.stopTest();        
    }
}