src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Current_Diagnosis__c</fullName>
        <description>Current Diagnosis</description>
        <inlineHelpText>If more than three diagnoses, list as 1. 2. 3. 4. etc.

For one to three diagnoses, write as narrative.</inlineHelpText>
        <label>Current Diagnosis</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Current_Prognosis__c</fullName>
        <description>Current Prognosis</description>
        <inlineHelpText>Indicate excellent, good, fair, poor followed by description of anticipated recovery status. Also include  which criteria this is based upon i.e. PTP, consulting MD, ACOEM, ADA, NCM.</inlineHelpText>
        <label>Current Prognosis</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Employee_Case_Trakker__c</fullName>
        <label>Employee (Case Trakker)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Employee</description>
        <label>Employee</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Open Files (Cases)</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Jurisdiction__c</fullName>
        <description>State where the file is being managed.</description>
        <inlineHelpText>Select the State where the File is being managed.</inlineHelpText>
        <label>Jurisdiction</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>California-WC</fullName>
                </value>
                <value>
                    <fullName>Nevada-WC</fullName>
                </value>
                <value>
                    <fullName>New Mexico-WC</fullName>
                </value>
                <value>
                    <fullName>Arizona-WC</fullName>
                </value>
                <value>
                    <fullName>Educational Services</fullName>
                </value>
                <value>
                    <fullName>Ergo. Eval.</fullName>
                </value>
                <value>
                    <fullName>LCP</fullName>
                </value>
                <value>
                    <fullName>LMS</fullName>
                </value>
                <value>
                    <fullName>EWT</fullName>
                </value>
                <value>
                    <fullName>Seminars</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Nature_and_History_of_Injury__c</fullName>
        <description>Nature &amp; History of Injury</description>
        <inlineHelpText>Include mechanism of Injury, date of injury, and initial symptoms.</inlineHelpText>
        <label>Nature &amp; History of Injury</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>QB_Service_Item__c</fullName>
        <description>QB Service Item</description>
        <label>QB Service Item</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ER</fullName>
                </value>
                <value>
                    <fullName>Ergo. Eval.</fullName>
                </value>
                <value>
                    <fullName>Interactive Process</fullName>
                </value>
                <value>
                    <fullName>EWT</fullName>
                </value>
                <value>
                    <fullName>Expenses</fullName>
                </value>
                <value>
                    <fullName>Job Analysis</fullName>
                </value>
                <value>
                    <fullName>LCP</fullName>
                </value>
                <value>
                    <fullName>LMS</fullName>
                </value>
                <value>
                    <fullName>Longshore-Voc</fullName>
                </value>
                <value>
                    <fullName>LTD</fullName>
                </value>
                <value>
                    <fullName>MCM-CAT</fullName>
                </value>
                <value>
                    <fullName>MCM-On Site</fullName>
                </value>
                <value>
                    <fullName>MCM-Tele</fullName>
                </value>
                <value>
                    <fullName>Mileage</fullName>
                </value>
                <value>
                    <fullName>Seminars</fullName>
                </value>
                <value>
                    <fullName>Soc. Service</fullName>
                </value>
                <value>
                    <fullName>TCM Triage</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Travel/Wait</fullName>
                </value>
                <value>
                    <fullName>VRC</fullName>
                </value>
                <value>
                    <fullName>Discount</fullName>
                </value>
                <value>
                    <fullName>RUSH-MCM-On Site</fullName>
                </value>
                <value>
                    <fullName>RUSH-Mileage</fullName>
                </value>
                <value>
                    <fullName>RUSH-Travel/Wait</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supervised_by__c</fullName>
        <description>Supervised by</description>
        <label>Supervised by</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Denise Demianeau, RN, CCM</fullName>
                </value>
                <value>
                    <fullName>Catherine Kvasnicka, RN, MSN</fullName>
                </value>
                <value>
                    <fullName>Tanya Jutting-Loumakis, MA, CCM</fullName>
                </value>
                <value>
                    <fullName>Diane Campos, General Manager</fullName>
                </value>
                <value>
                    <fullName>Alysha Calderon</fullName>
                </value>
                <value>
                    <fullName>Senior Mentor</fullName>
                </value>
                <value>
                    <fullName>Angie Jung, RN, BSN, CRRN, CCM</fullName>
                </value>
                <value>
                    <fullName>Contractor - Not Applicable</fullName>
                </value>
                <value>
                    <fullName>Whitney Boyles, RN, BSN, MS, CCM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Amount_Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Amount Locked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Current_Prognosis__c</fullName>
        <description>Current Prognosis</description>
        <inlineHelpText>Indicate excellent, good, fair, poor followed by description of anticipated recovery status. Also include  which criteria this is based upon i.e. PTP, consulting MD, ACOEM, ADA, NCM.</inlineHelpText>
        <label>Current Prognosis</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lookup Employee associated to the Report</inlineHelpText>
        <label>Employee</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Case_Reports_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Employer_Status__c</fullName>
        <label>Employer Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Modified Duty available, as indicated by Claims Professional</fullName>
                </value>
                <value>
                    <fullName>Modified Duty available, as indicated by Employer</fullName>
                </value>
                <value>
                    <fullName>Modified Duty unavailable, as indicated by Claims Professional</fullName>
                </value>
                <value>
                    <fullName>Modified Duty unavailable, as indicated by Employer</fullName>
                </value>
                <value>
                    <fullName>Available modified duty pending confirmation</fullName>
                </value>
                <value>
                    <fullName>Modified duty not applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>I_Will__c</fullName>
        <inlineHelpText>Document the NCM plan of action.  Planned activities that will be completed to achieve file resolution must appear here as statements of action stating &quot;I will&quot;, etc. Include who, what, when and where for each item.</inlineHelpText>
        <label>I Will</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Jurisdiction__c</fullName>
        <formula>TEXT ( Related_Case__r.Jurisdiction__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Jurisdiction</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QB_Service_Item__c</fullName>
        <formula>Text(Related_Case__r.QB_Service_Item__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>QB Service Item</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Remain_U_C__c</fullName>
        <description>Remain U&amp;C</description>
        <inlineHelpText>Select With Modifications or Without Modifications, No or Not Applicable; this should reflect what the physician prescribed for work status.  If &quot;Not applicable&quot; is selected, please explain in the comment section.</inlineHelpText>
        <label>Remain U&amp;C</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>With Modifications</fullName>
                </value>
                <value>
                    <fullName>Without Modifications</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Not applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Date_Thru__c</fullName>
        <description>Service Date Thru</description>
        <label>Service Date Thru</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status_of_EE_Job_Analysis_JA__c</fullName>
        <description>Status of EE Job Analysis (JA)</description>
        <inlineHelpText>Select from pick list</inlineHelpText>
        <label>Status of EE Job Analysis (JA)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Job Analysis not available, recommended authorization for ISYS Vocational Specialist to complete</fullName>
                </value>
                <value>
                    <fullName>Job Analysis  authorized, pending completion</fullName>
                </value>
                <value>
                    <fullName>Job Analysis recommended by CM, not requested by physician</fullName>
                </value>
                <value>
                    <fullName>Job Analysis recommended by CM, not authorized</fullName>
                </value>
                <value>
                    <fullName>Job Analysis  available and received</fullName>
                </value>
                <value>
                    <fullName>Job Analysis  requested pending response</fullName>
                </value>
                <value>
                    <fullName>Job Analysis requested pending receipt</fullName>
                </value>
                <value>
                    <fullName>Job Analysis provided to physician</fullName>
                </value>
                <value>
                    <fullName>Job Analysis not applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status_of_EE_Job_Descriptions_JD__c</fullName>
        <label>Status of EE Job Descriptions (JD)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>JD available and received</fullName>
                </value>
                <value>
                    <fullName>JD requested pending response</fullName>
                </value>
                <value>
                    <fullName>JD requested pending receipt</fullName>
                </value>
                <value>
                    <fullName>JD provided to physician&apos;</fullName>
                    <label>JD provided to physician</label>
                </value>
                <value>
                    <fullName>JD not available</fullName>
                </value>
                <value>
                    <fullName>JD not applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TTD__c</fullName>
        <description>TTD</description>
        <inlineHelpText>Select Yes, No or Not Applicable.</inlineHelpText>
        <label>TTD</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Test_CaseAfterUpdate.cls
@isTest
private class Test_CaseAfterUpdate {

    static testMethod void myUnitTest() {
        Case c = new Case();
        c.Supervised_by__c = 'MySelf';
        c.Status = 'Open';
        c.QB_Service_Item__c = 'ER';
        c.Priority = 'High';
        c.Origin = 'Web';
        c.Nature_and_History_of_Injury__c = 'Nothing';
        c.Employee_Case_Trakker__c = 'Nothing';
        c.Current_Diagnosis__c = 'Fine';
        c.Jurisdiction__c = 'Jurisdiction__c OLD';
        c.QB_Service_Item__c = 'QB_Service_Item__c OLD';
        insert c;
        
        Account a = new Account();
		a.Name = 'ACC1';
		insert a;
        
        Opportunity o = new Opportunity();
		o.AccountId = a.id;
		o.Name = 'test o1';
		o.Employee__c = a.Id;
		o.Service_Date_Thru__c = system.today();
		o.CloseDate = system.today();
		o.StageName = 'In Process';
		o.Amount_Locked__c = false;
		o.Current_Prognosis__c = 'Hi';
		o.TTD__c = 'sdfsdf';
		o.Status_of_EE_Job_Descriptions_JD__c = 'JD Not Applicable'; 
		o.Status_of_EE_Job_Analysis_JA__c = 'JA Not Applicable'; 
		o.Remain_U_C__c = 'sdfsdf'; 
		o.I_Will__c = 'I Will'; 
		o.Employer_Status__c = 'Employer'; 
		o.Employee_Status__c = 'Employee'; 
		o.Employee_Motivation_to_Return_to_Work__c = 'sdfsdf'; 
		o.Diagnostics_Evidence_Based_Information__c = 'sdfsdf'; 
		o.Current_Work_Status__c = 'asdad'; 
		o.Current_Treatment__c = 'asdad'; 
		o.Current_Prognosis__c = 'adad';
		o.Related_Case__c = c.Id;
		insert o;
        
        
        c.Origin = 'Phone';
        c.Jurisdiction__c = 'Jurisdiction__c New';
        c.QB_Service_Item__c = 'QB_Service_Item__c New';
        update c;
        
        
        
    }
}