src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Employee_Case_Trakker__c</fullName>
        <label>Employee (Case Trakker)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Primary Campaign</description>
        <label>Primary Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Related_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Reports</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/PopulateCampaignSource_Test.cls
@isTest
private class PopulateCampaignSource_Test{

    public Static TestMethod void PopulateCampaignSourceTest(){
    
        Campaign camp = New Campaign(Name='Test Campaign');
        insert camp;
        
        Case c = New Case(Status='Open', Employee_Case_Trakker__c='XYZ', Primary_Campaign__c=camp.Id);
        insert c;
        
        Opportunity oppt = new Opportunity(StageName='In Process', Name='Test Opportunity', CloseDate=System.Today(), Related_Case__c=c.Id);
        insert oppt;
    }
}