src/objects/Case_Note_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Professional_Hours_Nurse__c</fullName>
        <label>Professional Hours (Nurse)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Report__c</fullName>
        <description>Report</description>
        <inlineHelpText>Case Report that Entry is related to</inlineHelpText>
        <label>Report</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Case Note Entries</relationshipLabel>
        <relationshipName>Case_Note_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Case Note Entry</label>
    <nameField>
        <displayFormat>Bill-{00000}</displayFormat>
        <label>Case Note Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Note Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>A_Note_Approval_Date_Time__c</fullName>
        <description>A Note Approval Date / Time</description>
        <label>A Note Approval Date / Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>B_Note_Approval_Date_Time__c</fullName>
        <label>B Note Approval Date / Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lookup Employee associated to the Report</inlineHelpText>
        <label>Employee</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Case_Reports_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QBJurisdiction__c</fullName>
        <description>This field is being used in code and in the QB synch.  Please do not modify and/or delete.</description>
        <label>Jurisdiction</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QBServiceItem__c</fullName>
        <label>QB Service Item</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Date_Thru__c</fullName>
        <description>Service Date Thru</description>
        <label>Service Date Thru</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>QB_Initials__c</fullName>
        <description>Used for REP name in Quickbooks.</description>
        <label>QB Initials</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CG_OpportunityHandlerTest.cls
@isTest
private class CG_OpportunityHandlerTest {

	private static TestMethod void ProcessTest() {
                
        User u = new User();
	      User thisUser = [ select Id from User where Id = :UserInfo.getUserId() ];
    System.runAs ( thisUser ) {
        u.FirstName = 'Test'; 
        u.LastName = 'User';
        u.QB_Initials__c = 'TU';
        u.Username= 'testuserCGCG@CGcompany.com'; 
        u.Email = 'testuser@company.com';
        u.Alias = 'utest';
        u.TimeZoneSidKey = 'America/Denver';
        u.LocaleSidKey = 'en_US';
        u.EmailEncodingKey = 'UTF-8';
        u.ProfileId = [SELECT Id
        				 FROM Profile
						WHERE Name = 'Custom - Nurse'].Id;
        u.LanguageLocaleKey = 'en_US';
        insert u;
    }
          
       	Account acc = new Account();
		acc.Name = 'Test';
        acc.OwnerId = u.id;
        acc.Type = 'Employer';
		insert acc;
        
        Account pacc = new Account();
        pacc.FirstName = 'John';
 		pacc.LastName = 'Smith';
 		insert pacc;
		
		Opportunity opp = new Opportunity();
		opp.CloseDate = Date.TODAY();
		opp.StageName = 'Completed';
		opp.AccountId = acc.Id;
		opp.QBJurisdiction__c = 'California-WC';
		opp.Name = 'Test opp';
        opp.QBServiceItem__c = 'MCM-On SIte';
        opp.Employee__c = pacc.id;
        opp.Service_Date_Thru__c = Date.TODAY();
        opp.B_Note_Approval_Date_Time__c = null;
        opp.A_Note_Approval_Date_Time__c = null;
		insert opp;     
 
        Case_Note_Entry__c caseN1 = new Case_Note_Entry__c();
	    caseN1.Report__c = opp.Id;
	    caseN1.Professional_Hours_Nurse__c = 2.0;
        insert caseN1;
	    
	    Case_Note_Entry__c caseN2 = new Case_Note_Entry__c();
	    caseN2.Report__c = opp.Id;
	    caseN2.Professional_Hours_Nurse__c = 2.0;
        insert caseN2;
        
        opp = [SELECT id
              	FROM Opportunity
              LIMIT 1];
  
	    Opportunity Opp1 = new Opportunity();
        Opp1.Id = opp.id;
        opp1.QBServiceItem__c = 'RUSH-MCM-On Site';
	    Opp1.B_Note_Approval_Date_Time__c = dateTime.now();
        Opp1.A_Note_Approval_Date_Time__c = dateTime.now();
	    update Opp1;
               
 
	}
}