src/objects/Case_Note_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Date__c</fullName>
        <description>Activity Date</description>
        <inlineHelpText>Date activity took place</inlineHelpText>
        <label>Activity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Adj_Expenses__c</fullName>
        <description>Adj. Expenses</description>
        <label>Adj. Expenses</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Adj_Professional_Hours__c</fullName>
        <description>Adj. Professional Hours</description>
        <inlineHelpText>Audit: Invoice Time to QB</inlineHelpText>
        <label>Adj. Professional Hours</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expenses_Nurse__c</fullName>
        <label>Expenses (Nurse)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expenses__c</fullName>
        <description>Expenses</description>
        <label>Expenses</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Professional_Hours_Nurse__c</fullName>
        <label>Professional Hours (Nurse)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Professional_Hours__c</fullName>
        <description>Professional Hours</description>
        <inlineHelpText>Edit : Nurse Professional Time to QB</inlineHelpText>
        <label>Professional Units</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Report__c</fullName>
        <description>Report</description>
        <inlineHelpText>Case Report that Entry is related to</inlineHelpText>
        <label>Report</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Case Note Entries</relationshipLabel>
        <relationshipName>Case_Note_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Work_Description__c</fullName>
        <description>Work Description</description>
        <inlineHelpText>Description of work being performed or recorded</inlineHelpText>
        <label>Work Description</label>
        <type>TextArea</type>
    </fields>
    <label>Case Note Entry</label>
    <nameField>
        <displayFormat>Bill-{00000}</displayFormat>
        <label>Case Note Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Note Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>In_Review__c</fullName>
        <label>In Review</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>P_S_Comment__c</fullName>
        <description>Assessment Comment</description>
        <inlineHelpText>Address current status, why they are approaching P&amp;S/S&amp;R/Stationary status or why they are not.</inlineHelpText>
        <label>Assessment Comment</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Service_Date_From__c</fullName>
        <description>Service Date From</description>
        <label>Service Date From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_Date_Thru__c</fullName>
        <description>Service Date Thru</description>
        <label>Service Date Thru</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/OpportunityApprovalQueueControllerTest.cls
@IsTest
private class OpportunityApprovalQueueControllerTest 
{
    testMethod static void testOpportunityApprovalQueueController() 
    {
        Account testAccount = new Account();
        testAccount.Name = 'Test Account';
        insert testAccount;
        
        Opportunity testOpp = new Opportunity();
        testOpp.Name = 'Test Opp';
        testOpp.AccountId = testAccount.Id;
        testOpp.StageName = 'In Process';
        testOpp.CloseDate = System.today();
        testOpp.P_S_Comment__c = 'Test';
        testOpp.In_Review__c = 'No';
        testOpp.Service_Date_From__c = System.today();
        testOpp.Service_Date_Thru__c = System.today();
        insert testOpp;
        
        Case_Note_Entry__c testCaseNote = new Case_Note_Entry__c();
        testCaseNote.Expenses__c = 10;                
        testCaseNote.Professional_Hours__c = 10;
        testCaseNote.Report__c = testOpp.Id;
        testCaseNote.Adj_Professional_Hours__c = 0;        
        testCaseNote.Adj_Expenses__c = 10;        
        testCaseNote.Professional_Hours_Nurse__c = 1;                
        testCaseNote.Expenses_Nurse__c = 1;
        testCaseNote.Work_Description__c = 'Test';
        testCaseNote.Activity_Date__c=Date.today();
        insert testCaseNote;
        
        Approval.ProcessSubmitRequest testRequest = new Approval.ProcessSubmitRequest();
        testRequest.setComments('Submitting request for approval.');
        testRequest.setObjectId(testOpp.Id);
        
        Approval.ProcessResult result = Approval.process(testRequest);
        
        User approverUser = new User();
        List<ProcessInstanceWorkitem> workitems = [SELECT Id, ActorId, Actor.Id, Actor.Name FROM ProcessInstanceWorkitem WHERE ProcessInstance.TargetObjectId=:testOpp.Id limit 1];
        if (!workitems.isEmpty()) 
        {
            approverUser = [SELECT Id, Name FROM User WHERE Id =: workitems[0].ActorId];
            System.debug('Run As: ' + approverUser.Name);
        }
        
        // Create and initialize our controller
        System.runAs(approverUser) 
        {
            Test.startTest();
            
            PageReference testPage = Page.OpportunityApprovalQueue;
            Test.setCurrentPage(testPage);
            
            OpportunityApprovalQueueController controller = new OpportunityApprovalQueueController();
            controller.InitializeController();
            
            Test.stopTest();
        }
    }       
}