src/objects/CompanyMetric__c.object
<CustomObject>
    <fields>
        <fullName>AdminStaff__c</fullName>
        <label>SRS Staff</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseManagers__c</fullName>
        <label>Case Managers</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Holds month/year as the external key</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>QAStaff__c</fullName>
        <description>Number of Active QA Staff.</description>
        <label>QA Staff</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Company Metric</label>
    <nameField>
        <displayFormat>Metric-{0000000000}</displayFormat>
        <label>Company Metric Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Company Metrics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>AssignedArea__c</fullName>
        <label>Assigned Area</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>201</fullName>
                </value>
                <value>
                    <fullName>203</fullName>
                </value>
                <value>
                    <fullName>205</fullName>
                </value>
                <value>
                    <fullName>206</fullName>
                </value>
                <value>
                    <fullName>208</fullName>
                </value>
                <value>
                    <fullName>209</fullName>
                </value>
                <value>
                    <fullName>210</fullName>
                </value>
                <value>
                    <fullName>212</fullName>
                </value>
                <value>
                    <fullName>213</fullName>
                </value>
                <value>
                    <fullName>214</fullName>
                </value>
                <value>
                    <fullName>215</fullName>
                </value>
                <value>
                    <fullName>216</fullName>
                </value>
                <value>
                    <fullName>217</fullName>
                </value>
                <value>
                    <fullName>218</fullName>
                </value>
                <value>
                    <fullName>219</fullName>
                </value>
                <value>
                    <fullName>224</fullName>
                </value>
                <value>
                    <fullName>225</fullName>
                </value>
                <value>
                    <fullName>228</fullName>
                </value>
                <value>
                    <fullName>229</fullName>
                </value>
                <value>
                    <fullName>231</fullName>
                </value>
                <value>
                    <fullName>234</fullName>
                </value>
                <value>
                    <fullName>239</fullName>
                </value>
                <value>
                    <fullName>240</fullName>
                </value>
                <value>
                    <fullName>248</fullName>
                </value>
                <value>
                    <fullName>251</fullName>
                </value>
                <value>
                    <fullName>252</fullName>
                </value>
                <value>
                    <fullName>253</fullName>
                </value>
                <value>
                    <fullName>254</fullName>
                </value>
                <value>
                    <fullName>256</fullName>
                </value>
                <value>
                    <fullName>260</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestBatchCompanyMetricUser.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestBatchCompanyMetricUser 
{
    static List<User> uList = new List<User>();
    static testMethod void myUnitTest() 
    {
        BatchCompanyMetricUser mUser = new BatchCompanyMetricUser();
        uList = [Select Id,Profile.Name FROM User where Id in :uList];
        mUser.execute(null, uList);
        mUser.finish(null);
        
        CompanyMetric__c cm = [SELECT CaseManagers__c,AdminStaff__c,QAStaff__c FROM CompanyMetric__c WHERE ExternalId__c=:mUser.runDateMonthYear];
        System.assertEquals(1,cm.CaseManagers__c);
        System.assertEquals(1,cm.AdminStaff__c);
        System.assertEquals(1,cm.QAStaff__c);
    }
    static testMethod void testSchedulable()
    {
    	Test.startTest();        
    	String cron = '0 0 0 17 11 ? 2033';
    	System.schedule('BATR99zz', cron, new BatchCompanyMetricUserSchedulable());
    	Test.stopTest();
    }
    static
    {
    	integer i=0;
    	for(Profile p : [SELECT Id FROM Profile WHERE Name in ('Custom - Nurse','Custom - Admin Staff','Custom - QA Staff')])
    	{
    		uList.add(new User(UserName='test@isys.com'+i,email='test@isys.com',alias='tisys'+i,communitynickname='tix'+i,TimeZoneSidKey='America/New_York',LocaleSidKey='en_US',EmailEncodingKey='ISO-8859-1',ProfileId=p.Id,LanguageLocaleKey='en_US',FirstName='Test',LastName='User',IsActive=true,AssignedArea__c='706;707;708;'));
    		i++;
    	}
    	insert uList;    	
    }
}