src/objects/CompanyMetric__c.object
<CustomObject>
    <fields>
        <fullName>CasesClosed__c</fullName>
        <label>Cases (Closed)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CasesOpen__c</fullName>
        <label>Cases (Open)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CasesReOpened__c</fullName>
        <label>Cases (Re-Opened)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Holds month/year as the external key</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MonthEnding__c</fullName>
        <label>Month Ending</label>
        <type>Date</type>
    </fields>
    <label>Company Metric</label>
    <nameField>
        <displayFormat>Metric-{0000000000}</displayFormat>
        <label>Company Metric Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Company Metrics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchCompanyMetricCase.cls
global class BatchCompanyMetricCase implements Database.Batchable<sObject>, Database.Stateful
{
	private Date runDate = Date.today();    
    private integer daysInMonth = Date.daysInMonth(runDate.year(),runDate.month()); 
    private Date metricDate = Date.parse(String.valueOf(runDate.month())+'/'+daysInMonth+'/'+runDate.year());
    public String runDateMonthYear = String.valueOf(runDate.month()+'/'+runDate.year());
    private CompanyMetric__c cm = new CompanyMetric__c(ExternalId__c=runDateMonthYear,MonthEnding__c=metricDate,CasesOpen__c=0,CasesReOpened__c=0,CasesClosed__c=0);
	private integer currentMonth = runDate.month();
	private integer currentYear = runDate.year();
	
	global Database.Querylocator start(Database.Batchablecontext BC)
    {       
        return Database.getQueryLocator([Select Id,Status,ClosedDate FROM Case WHERE Status in ('Open','Re-Opened','Closed')]);
    }
    global void execute(Database.Batchablecontext BC, list<Case> scope)
    {
    	for(Case c : scope)
    	{
    		if(c.Status=='Open')
    			cm.CasesOpen__c+=1;
    		else if(c.Status=='Re-Opened')
    			cm.CasesReOpened__c+=1;
    		else if(c.Status=='Closed' && (c.ClosedDate.month()==currentMonth && c.ClosedDate.year()==currentYear))
    			cm.CasesClosed__c+=1;
    	}
    }
    global void finish (Database.Batchablecontext BC)
    {
        upsert cm ExternalId__c;
    }
}