src/objects/Healthcare_Provider__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Other_Healthcare_Providers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact</description>
        <inlineHelpText>Healthcare Provider</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Other_Healthcare_Providers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Previous, but inactive treaters on the case</description>
        <inlineHelpText>Designate a Healthcare Provider as inactive when the Employee is no longer treating with them</inlineHelpText>
        <label>Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mailing_Address__c</fullName>
        <formula>Contact__r.MailingStreet &amp;&quot; &quot;&amp;Contact__r.MailingCity&amp;&quot; &quot;&amp;Contact__r.MailingState&amp;&quot; &quot;&amp;Contact__r.MailingPostalCode&amp;&quot; &quot;&amp;Contact__r.MailingCountry</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mailing Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <formula>Contact__r.Phone</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Primary</description>
        <inlineHelpText>Only one physician can be designated as Primary Health Care Provider.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Specialty__c</fullName>
        <description>Specialty</description>
        <inlineHelpText>Specialty of healthcare provider</inlineHelpText>
        <label>Specialty</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Healthcare Provider</label>
    <nameField>
        <displayFormat>HP-{000000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Healthcare Providers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Contact #</description>
        <label>Contact #</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lookup Employee associated to the Report</inlineHelpText>
        <label>Employee</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Case_Reports_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Reports</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CT_HealthcareProviderHelper.cls
public with sharing class CT_HealthcareProviderHelper
{
	private String CLASSNAME = '\n\n**** CT_HealthcareProviderHelper.@@METHODNAME()';

	//@author : CloudTrigger, Inc.
	//@date : 3/12/2012
	//@description : method to 
	//@paramaters : none
	//@returns : nothing
    public static CT_HealthcareProviderHelper NewHelper()
    {
    	CT_HealthcareProviderHelper newModel = new CT_HealthcareProviderHelper();
    	return newModel;
    }

	//@author : CloudTrigger, Inc.
	//@date : 3/12/2012
	//@description : method to 
	//@paramaters : none
	//@returns : nothing
    private CT_HealthcareProviderHelper()
    {
    }
    
	//@author : CloudTrigger, Inc.
	//@date : 3/12/2012
	//@description : method to GetHealthcareProviderListByOpportunityId
	//@paramaters : a String representing the ID of an Opportunity
	//@returns : a collection of Healthcare_Provider__c records
    public list<Healthcare_Provider__c> GetHealthcareProviderListByOpportunityId(String pOpportunityId)
    {
    	String METHODNAME = CLASSNAME.replace('@@METHODNAME', 'GetHealthcareProviderListByOpportunityId');
    	system.debug(LoggingLevel.INFO, METHODNAME.replace('**** ', '**** Inside ') + ' \n\n');

    	list<Healthcare_Provider__c> HealthcareProviderList = new list<Healthcare_Provider__c>([Select h.Contact__r.Name, h.Name, h.Contact__c, h.Phone__c, h.Mailing_Address__c, 
                h.Specialty__c, h.Primary__c, h.Contact__r.FirstName, h.Contact__r.LastName  From Healthcare_Provider__c h Where 
                h.Inactive__c <> true and h.Case__c in 
                (Select Related_Case__c From Opportunity Where Id =: pOpportunityId)]);
        return HealthcareProviderList;
    }
    
	//@author : CloudTrigger, Inc.
	//@date : 3/12/2012
	//@description : method to GetOpportunityListByOpportunityId
	//@paramaters : a String representing the ID of an Opportunity
	//@returns : a collection of Opportunity records
    public list<Opportunity> GetOpportunityListByOpportunityId(String pOpportunityId)
    {
    	String METHODNAME = CLASSNAME.replace('@@METHODNAME', 'GetOpportunityListByOpportunityId');
    	system.debug(LoggingLevel.INFO, METHODNAME.replace('**** ', '**** Inside ') + ' \n\n');

    	list<Opportunity> OpptyList = new list<Opportunity>([Select Name, Employee__c From Opportunity Where Id =: pOpportunityId]);
        return OpptyList;
    }
    
	//@author : CloudTrigger, Inc.
	//@date : 3/12/2012
	//@description : method to GetHealthcareProviderListByOpportunityId
	//@paramaters : a String representing the ID of an Opportunity
	//@returns : a collection of Healthcare_Provider__c records
    public list<Healthcare_Provider__c> GetPrimaryHealthcareProviderListByOpportunityId(String pOpportunityId)
    {
    	String METHODNAME = CLASSNAME.replace('@@METHODNAME', 'GetPrimaryHealthcareProviderListByOpportunityId');
    	system.debug(LoggingLevel.INFO, METHODNAME.replace('**** ', '**** Inside ') + ' \n\n');

    	list<Healthcare_Provider__c> HealthcareProviderList = new list<Healthcare_Provider__c>([Select h.Contact__r.Name, h.Contact__r.FirstName, h.Contact__r.LastName 
	            																		From Healthcare_Provider__c h 
	                																	Where h.Case__c in (Select Related_Case__c 
	                																						From Opportunity 
	                																						Where Id =: pOpportunityId) 
    																						and Primary__c = true]);
        return HealthcareProviderList;
    }


}