src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>A_Note_Approval_Date_Time__c</fullName>
        <description>A Note Approval Date / Time</description>
        <label>A Note Approval Date / Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>B_Note_Approval_Date_Time__c</fullName>
        <label>B Note Approval Date / Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lookup Employee associated to the Report</inlineHelpText>
        <label>Employee</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Case_Reports_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QBJurisdiction__c</fullName>
        <description>This field is being used in code and in the QB synch.  Please do not modify and/or delete.</description>
        <label>Jurisdiction</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QBServiceItem__c</fullName>
        <label>QB Service Item</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Date_Thru__c</fullName>
        <description>Service Date Thru</description>
        <label>Service Date Thru</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>QB_Initials__c</fullName>
        <description>Used for REP name in Quickbooks.</description>
        <label>QB Initials</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CG_OpportunityTriggerTest.cls
@isTest
private class CG_OpportunityTriggerTest {

    private static TestMethod void ProcessBTest() {
        
        User u = new User();
	      User thisUser = [ select Id from User where Id = :UserInfo.getUserId() ];
    System.runAs ( thisUser ) {
        u.FirstName = 'Test'; 
        u.LastName = 'User';
        u.QB_Initials__c = 'TU';
        u.Username= 'testuserCGCG@Ccompany.com'; 
        u.Email = 'testuser@company.com';
        u.Alias = 'utest';
        u.TimeZoneSidKey = 'America/Denver';
        u.LocaleSidKey = 'en_US';
        u.EmailEncodingKey = 'UTF-8';
        u.ProfileId = [SELECT Id
                         FROM Profile
                        WHERE Name = 'Custom - Nurse'].Id;
        u.LanguageLocaleKey = 'en_US';
        insert u;
    }
        
        Account acc = new Account();
        acc.Name = 'Test';
        acc.OwnerId = u.id;
        insert acc;
        
        Account pacc = new Account();
        pacc.FirstName = 'John';
        pacc.LastName = 'Smith';
        insert pacc;
        
        Opportunity opp = new Opportunity();
        opp.CloseDate = Date.TODAY();
        opp.StageName = 'Completed';
        opp.AccountId = acc.Id;
        opp.QBJurisdiction__c = 'California-WC';
        opp.Name = 'Test opp';
        opp.QBServiceItem__c = 'MCM-On SIte';
        opp.Employee__c = pacc.id;
        opp.Service_Date_Thru__c = Date.TODAY();
        opp.B_Note_Approval_Date_Time__c = null;
        insert opp;
        
        Opportunity newOpp = new Opportunity();
        newOpp.Id = opp.Id;
        newOpp.B_Note_Approval_Date_Time__c = dateTime.now();
        newOpp.A_Note_Approval_Date_Time__c = dateTime.now();
        update newOpp;
        
        Opportunity noDateOpp = new Opportunity();
        noDateOpp.Id = opp.Id;
        noDateOpp.B_Note_Approval_Date_Time__c = null;
        noDateOpp.A_Note_Approval_Date_Time__c = null;
        update noDateOpp;
        
        Opportunity upOpp = new Opportunity();
        upOpp.Id = opp.Id;
        upOpp.B_Note_Approval_Date_Time__c = dateTime.now();
        upOpp.B_Note_Approval_Date_Time__c = dateTime.now();
        update upOpp;
        
    
    }

}